import type { NodeSpec, NodeType, Parameter, Port, PortType } from './types'

const n = (key: string, label: string, value: number, min = -1000000, max = 1000000, step = 0.1): Parameter => ({ kind: 'number', key, label, default: value, min, max, step })
const choice = (key: string, label: string, options: string[]): Parameter => ({ kind: 'select', key, label, default: options[0]!, options })
const port = (type: PortType, name: string, label: string, input = true): Port => ({ id: `${input ? 'in' : 'out'}:${type}:${name}`, label, type })
const frameIn = port('frame', 'image', 'Frame'), frameOut = port('frame', 'image', 'Frame', false)
const pair = [port('frame', 'a', 'Frame A'), port('frame', 'b', 'Frame B')]
const radius = n('radius', 'Radius · px', 1, 1, 32, 1)
const spec = (type: NodeType, title: string, category: string, algorithm: string, description: string, parameters: Parameter[] = [], inputs: Port[] = [frameIn], outputs: Port[] = [frameOut]): NodeSpec => ({ type, title, category, algorithm, description, parameters, inputs, outputs, version: 1 })
const scalarOut = port('scalar', 'value', 'Value', false)
const axes = [n('x', 'X', 0), n('y', 'Y', 0)]
const size = [n('width', 'Width · px', 320, 1, 8192, 1), n('height', 'Height · px', 180, 1, 8192, 1)]

/** Native operations and small value primitives. Every parameter becomes a typed socket. */
export const CATALOG: NodeSpec[] = [
  spec('clip', 'Video Source', 'Input', 'File → indexed video clip', 'A video is a clip, not an image. Connect its Video socket to Extract Video Frame and supply a frame index.', [], [], [port('video', 'clip', 'Video clip', false)]),
  spec('readFrame', 'Extract Video Frame', 'Video', 'Video + index → decoded frame', 'Decode one exact, zero-based frame from a video. Connect Time → Frame index for playback, or a Number to inspect a fixed drawing.', [n('frame', 'Frame index', 0, 0, 1000000000, 1)], [port('video', 'clip', 'Video clip')]),
  spec('videoInfo', 'Video Info', 'Video', 'Read clip metadata', 'Read a clip’s dimensions, frame count, frame rate and duration without decoding a frame.', [], [port('video', 'clip', 'Video clip')], ['width', 'height', 'frames', 'fps', 'seconds'].map(key => port('scalar', key, key === 'frames' ? 'Frame count' : key === 'fps' ? 'Frames / second' : key, false))),
  spec('imageInfo', 'Frame Size', 'Frame', 'Mat.cols · Mat.rows', 'Read the dimensions of this exact image, including a crop or pyramid level. Use these outputs to drive another node’s size.', [], [frameIn], [port('scalar', 'width', 'Width', false), port('scalar', 'height', 'Height', false)]),
  spec('text', 'Text', 'Input', 'String value', 'A reusable text value. Connect it to a text or algorithm-option input; option inputs validate the supplied string.', [{ kind: 'text', key: 'value', label: 'Text', default: '', maxLength: 4096 }], [], [port('string', 'value', 'Text', false)]),
  spec('boolean', 'Boolean', 'Input', 'Boolean value', 'An explicit true/false value for masks, comparisons and switches.', [{ kind: 'boolean', key: 'value', label: 'Value', default: false }], [], [port('boolean', 'value', 'Boolean', false)]),
  spec('vector', 'Vector 2D', 'Data', 'X + Y → vector', 'Package two numbers as a position or displacement, without changing their units.', axes, [], [port('vector', 'value', 'Vector', false)]),
  spec('rectangle', 'Rectangle', 'Data', 'X + Y + width + height → rectangle', 'Describe a rectangular region in pixels. The top-left corner is inclusive; width and height count pixels.', [n('x', 'Left · px', 0, 0, 1000000, 1), n('y', 'Top · px', 0, 0, 1000000, 1), ...size], [], [port('rect', 'value', 'Rectangle', false)]),
  spec('splitVector', 'Separate Vector', 'Data', 'Vector → X + Y', 'Expose each component so ordinary number nodes can modify a displacement.', [], [port('vector', 'value', 'Vector')], ['x', 'y'].map(key => port('scalar', key, key.toUpperCase(), false))),
  spec('splitRectangle', 'Separate Rectangle', 'Data', 'Rectangle → bounds', 'Expose a region’s position and size as numbers for resizing, positioning or custom calculations.', [], [port('rect', 'value', 'Rectangle')], ['x', 'y', 'width', 'height'].map(key => port('scalar', key, key, false))),
  spec('math', 'Math', 'Math', 'Scalar arithmetic', 'Combine numbers using add, subtract, divide, power, min, max, modulo, floor, ceil, round or absolute value. Division by zero and non-finite results report an error.', [choice('operation', 'Operation', ['add', 'subtract', 'multiply', 'divide', 'power', 'min', 'max', 'modulo', 'floor', 'ceil', 'round', 'absolute']), n('a', 'A', 0), n('b', 'B', 1)], [], [scalarOut]),
  spec('compare', 'Compare Numbers', 'Math', 'Comparison → boolean', 'Compare two computed values and produce a boolean for a switch or other boolean input.', [choice('operation', 'Operation', ['less', 'greater', 'equal', 'less or equal', 'greater or equal', 'not equal']), n('a', 'A', 0), n('b', 'B', 1)], [], [port('boolean', 'value', 'Result', false)]),
  spec('logic', 'Boolean Math', 'Math', 'AND · OR · NOT · XOR', 'Combine boolean conditions. NOT uses only A.', [choice('operation', 'Operation', ['and', 'or', 'not', 'xor']), { kind: 'boolean', key: 'a', label: 'A', default: false }, { kind: 'boolean', key: 'b', label: 'B', default: false }], [], [port('boolean', 'value', 'Result', false)]),
  spec('selectNumber', 'Switch Number', 'Math', 'Condition ? A : B', 'Choose A when the condition is true and B otherwise. Both input branches are evaluated.', [{ kind: 'boolean', key: 'condition', label: 'Condition', default: false }, n('a', 'When true', 1), n('b', 'When false', 0)], [], [scalarOut]),
  spec('coverage', 'Frame Coverage', 'Mask', 'Same-size white mask', 'Create a white mask covering this frame’s canvas. Transform it alongside the image, then threshold near 1 to identify pixels with complete source coverage. This measures geometric coverage, not object ownership.'),
  spec('crop', 'Crop Frame', 'Region', 'Mat.roi', 'Extract the rectangle as a new frame. Coordinates are relative to the input frame; regions outside it are rejected. Process this smaller image, then use Paste Region to put it back.', [], [frameIn, port('rect', 'region', 'Region')]),
  spec('paste', 'Paste Region', 'Region', 'ROI · copyTo', 'Copy a processed patch into a base frame at X/Y. The patch must fit. Pixels outside the patch stay unchanged.', [n('x', 'Left · px', 0, 0, 1000000, 1), n('y', 'Top · px', 0, 0, 1000000, 1)], [port('frame', 'base', 'Base frame'), port('frame', 'patch', 'Patch frame')]),
  spec('resize', 'Resize Frame', 'Transform', 'resize', 'Change the image dimensions. Area sampling is useful for shrinking; nearest preserves hard labels; linear and cubic interpolate spatially.', [...size, choice('method', 'Interpolation', ['linear', 'nearest', 'area', 'cubic'])]),
  spec('rotate', 'Rotate Frame', 'Transform', 'getRotationMatrix2D · warpAffine', 'Rotate around the image center on a canvas of the same size. Positive angles rotate counterclockwise; empty space is black.', [n('angle', 'Angle · degrees', 0, -3600, 3600), n('scale', 'Scale', 1, 0.01, 100, 0.01)]),
  spec('flip', 'Flip Frame', 'Transform', 'flip', 'Mirror the image horizontally, vertically or on both axes.', [choice('axis', 'Axis', ['horizontal', 'vertical', 'both'])]),
  spec('boxBlur', 'Box Blur', 'Filter', 'blur', 'Average a square neighborhood with equal weights. Radius r uses a (2r+1) × (2r+1) window.', [radius]),
  spec('medianBlur', 'Median Blur', 'Filter', 'medianBlur', 'Remove isolated specks by choosing the median of nearby samples. The frame is quantized to 8-bit before native median filtering, then returned as normalized float.', [radius]),
  spec('bilateral', 'Bilateral Filter', 'Filter', 'bilateralFilter', 'Smooth nearby pixels with similar colors while preserving stronger boundaries. Color sigma is in normalized 0…1 units.', [n('diameter', 'Diameter', 5, 1, 31, 1), n('sigmaColor', 'Color sigma', 0.1, 0.001, 2, 0.01), n('sigmaSpace', 'Spatial sigma', 5, 0.1, 100)]),
  spec('sobel', 'Sobel Derivative', 'Edges', 'Sobel', 'Measure signed brightness change along X or Y. Negative responses stay in floating point and appear around middle gray in the preview.', [choice('axis', 'Axis', ['x', 'y']), n('radius', 'Kernel radius', 1, 1, 3, 1), n('scale', 'Scale', 1, 0.001, 100)]),
  spec('scharr', 'Scharr Derivative', 'Edges', 'Scharr', 'Measure a signed derivative with a fixed 3×3 kernel that improves orientation symmetry over a small Sobel kernel.', [choice('axis', 'Axis', ['x', 'y']), n('scale', 'Scale', 1, 0.001, 100)]),
  spec('laplacian', 'Laplacian Derivative', 'Edges', 'Laplacian', 'Measure the second spatial derivative. This highlights fine changes; it is different from a Laplacian pyramid band.', [n('radius', 'Kernel radius', 1, 0, 3, 1), n('scale', 'Scale', 1, 0.001, 100)]),
  spec('canny', 'Canny Edges', 'Edges', 'Canny', 'Convert brightness to 8-bit, find gradients, thin edges and keep weak edges connected to strong ones. Thresholds use 0…255 intensity units.', [n('low', 'Low threshold', 50, 0, 255, 1), n('high', 'High threshold', 150, 0, 255, 1), { kind: 'boolean', key: 'l2', label: 'L2 gradient', default: true }]),
  spec('normalize', 'Normalize Frame', 'Color', 'normalize · NORM_MINMAX', 'Map the minimum RGB value to low and the maximum to high. Useful for viewing derivative and distance maps; it changes pixel values.', [n('low', 'Low', 0, -100, 100), n('high', 'High', 1, -100, 100)]),
  spec('invert', 'Invert Frame', 'Color', '1 − RGB', 'Invert RGB or a mask while keeping its alpha channel.'),
  spec('brightness', 'Scale and Offset', 'Color', 'RGB × gain + offset', 'Apply a linear intensity transform in normalized floating-point units. Values are not clipped until display or encoding.', [n('gain', 'Gain', 1, -100, 100), n('offset', 'Offset', 0, -100, 100)]),
  spec('adaptiveThreshold', 'Adaptive Threshold', 'Mask', 'adaptiveThreshold', 'Compare each 8-bit brightness value against a local mean or Gaussian mean minus C. Useful under uneven illumination.', [radius, n('c', 'C · 8-bit units', 2, -255, 255), choice('method', 'Local estimate', ['gaussian', 'mean']), { kind: 'boolean', key: 'invert', label: 'Invert', default: false }]),
  ...(['erode', 'dilate', 'morphology'] as const).map(type => spec(type, type === 'erode' ? 'Erode' : type === 'dilate' ? 'Dilate' : 'Morphology', 'Mask', type === 'morphology' ? 'morphologyEx' : type, type === 'erode' ? 'Take the neighborhood minimum, shrinking bright mask regions.' : type === 'dilate' ? 'Take the neighborhood maximum, expanding bright mask regions.' : 'Open removes small bright islands; close fills small holes; gradient isolates boundaries; top-hat and black-hat measure local contrast.', [radius, n('iterations', 'Iterations', 1, 1, 16, 1), choice('shape', 'Kernel shape', ['ellipse', 'rectangle', 'cross']), ...(type === 'morphology' ? [choice('operation', 'Operation', ['open', 'close', 'gradient', 'top hat', 'black hat'])] : [])])),
  spec('equalize', 'Equalize Histogram', 'Color', 'equalizeHist', 'Redistribute 8-bit grayscale brightness over its histogram. Outputs grayscale; this can amplify noise.'),
  spec('clahe', 'CLAHE', 'Color', 'createCLAHE', 'Equalize grayscale within local tiles while limiting contrast amplification.', [n('clipLimit', 'Clip limit', 2, 0.01, 100), n('tiles', 'Tiles per axis', 8, 1, 64, 1)]),
  spec('distanceTransform', 'Distance Transform', 'Mask', 'distanceTransform', 'Convert the mask to 8-bit and measure each nonzero pixel’s distance to the nearest zero pixel. Raw outputs are in pixels; use Normalize Frame to display the complete range.', [choice('metric', 'Metric', ['euclidean', 'manhattan', 'chessboard'])]),
  spec('pyrDown', 'Pyramid Down', 'Pyramid', 'pyrDown', 'Apply the Gaussian 5×5 pyramid kernel and keep every other sample. Output dimensions are ceil(width/2) × ceil(height/2).'),
  spec('pyrUp', 'Pyramid Up', 'Pyramid', 'pyrUp', 'Upsample and smooth a pyramid level. Zero dimensions mean exactly twice the input size; specify the original size when reconstructing an odd-sized image.', [n('width', 'Width · 0 = double', 0, 0, 8192, 1), n('height', 'Height · 0 = double', 0, 0, 8192, 1)]),
  spec('frameList', 'Make Pyramid Levels', 'Pyramid', 'Four frames → pyramid', 'Package four explicitly computed frames as Gaussian levels or Laplacian bands. The final Laplacian item is the coarse frame. Useful when building a pyramid from basic Down, Up and Subtract nodes.', [choice('kind', 'Pyramid type', ['gaussian', 'laplacian'])], [0, 1, 2, 3].map(i => port('frame', `level${i}`, `Level ${i}`)), [port('frames', 'levels', 'Pyramid', false)]),
  spec('gaussianPyramid', 'Gaussian Pyramid', 'Pyramid', 'Repeated pyrDown', 'Build a list from the original frame through progressively smoother half-resolution frames. Level 0 is the original; use Pyramid Level to select one.', [n('levels', 'Downsample levels', 3, 1, 10, 1)], [frameIn], [port('frames', 'levels', 'Gaussian levels', false)]),
  spec('laplacianPyramid', 'Laplacian Pyramid', 'Pyramid', 'Gaussian − expanded next level', 'Build signed detail bands plus the coarsest Gaussian frame. Each band stores exactly the detail lost between two scales. Use Reconstruct Pyramid to recover the original.', [n('levels', 'Downsample levels', 3, 1, 10, 1)], [frameIn], [port('frames', 'levels', 'Detail bands + coarse', false)]),
  spec('pyramidLevel', 'Pyramid Level', 'Pyramid', 'Frame list[index]', 'Select one frame or signed detail band from a pyramid. Level 0 has the original resolution.', [n('level', 'Level index', 0, 0, 10, 1)], [port('frames', 'levels', 'Pyramid')]),
  spec('reconstructPyramid', 'Reconstruct Pyramid', 'Pyramid', 'Repeated pyrUp + add', 'Starting at the coarsest level, upsample to each detail band’s exact size and add it back. Accepts a Laplacian pyramid, not a Gaussian pyramid.', [], [port('frames', 'levels', 'Laplacian pyramid')]),
  ...(['addImages', 'subtractImages', 'multiplyImages', 'blendImages'] as const).map(type => spec(type, { addImages: 'Add Frames', subtractImages: 'Subtract Frames', multiplyImages: 'Multiply Frames', blendImages: 'Mix Frames' }[type], 'Compose', { addImages: 'add', subtractImages: 'subtract · absdiff', multiplyImages: 'multiply', blendImages: 'addWeighted' }[type], type === 'subtractImages' ? 'Compare these exact two frames. No time offset is applied. Signed subtraction preserves negative differences; absolute difference shows change strength.' : type === 'blendImages' ? 'Compute A × (1 − factor) + B × factor. This is explicit blending and can create ghosting between different drawings.' : 'Combine matching pixels from two frames of the same size. Floating-point results preserve values beyond the display range.', type === 'subtractImages' ? [{ kind: 'boolean', key: 'absolute', label: 'Absolute difference', default: true }] : type === 'blendImages' ? [n('factor', 'Factor', 0.5, 0, 1, 0.01)] : [], pair)),
  spec('channel', 'Extract Channel', 'Color', 'extractChannel', 'Select R, G, B or alpha and display it as a grayscale frame.', [choice('channel', 'Channel', ['red', 'green', 'blue', 'alpha'])]),
  spec('mergeChannels', 'Combine RGB', 'Color', 'merge', 'Take the brightness channel from each input frame and combine them into one RGB image. Inputs must have matching dimensions.', [], ['red', 'green', 'blue'].map(key => port('frame', key, key))),
  spec('magnitude', 'Gradient Magnitude', 'Edges', 'magnitude', 'Combine horizontal and vertical grayscale derivatives as sqrt(X² + Y²). Use with Sobel or Scharr outputs.', [], [port('frame', 'x', 'X derivative'), port('frame', 'y', 'Y derivative')]),
  spec('phaseCorrelation', 'Estimate Translation', 'Measure', 'phaseCorrelate', 'Compare these exact two frames to estimate one global translation. Frame choice is explicit upstream. This is not a per-object motion field.', [], pair, [port('motion', 'shift', 'Translation', false), port('scalar', 'dx', 'Delta X · px', false), port('scalar', 'dy', 'Delta Y · px', false), port('scalar', 'response', 'Response', false)]),
  spec('coordinates', 'Image Coordinates', 'Generate', 'pixel positions → X / Y / U / V', 'Create coordinate images without an input image. U=x/width and V=y/height are normalized ramps; X and Y contain zero-based pixel positions. Feed them into Pixel Math to build gradients, stripes, circles, checkerboards and animation. Dimensions are explicit inputs.', [...size], [], [port('frame', 'u', 'U · x / width', false), port('frame', 'v', 'V · y / height', false), port('frame', 'x', 'X · pixels', false), port('frame', 'y', 'Y · pixels', false)]),
  spec('noise', 'Seeded Noise', 'Generate', 'seeded LCG → quantized uniform noise', 'Create repeatable grayscale noise without a video. The same seed and dimensions give the same values on every evaluation. Values are floor(random × levels) / levels, from zero up to but excluding one. Drive Seed from Time for changing noise, or leave it fixed for a stable texture.', [...size, n('seed', 'Seed', 412947, 0, 4294967295, 1), n('levels', 'Noise levels', 64, 2, 65536, 1)], [], [frameOut]),
  spec('pixelMath', 'Pixel Math', 'Math', 'per-pixel arithmetic', 'Apply an operation independently to each RGB component. A is an image; B is an optional image of the same size or the inline scalar. Sine and cosine use radians. Modulo wraps into a positive period; fraction is A minus floor(A). RGB stays floating point outside 0…1 until display. Alpha comes from A. Division or modulo by zero reports an error.', [choice('operation', 'Operation', ['add', 'subtract', 'multiply', 'divide', 'modulo', 'floor', 'ceil', 'round', 'fraction', 'absolute', 'sine', 'cosine', 'power', 'min', 'max', 'step', 'clamp']), n('b', 'Fallback B', 1)], [port('frame', 'a', 'A'), { ...port('frame', 'b', 'B image · optional'), optional: true }]),
  spec('farneback', 'Dense Optical Flow', 'Measure', 'calcOpticalFlowFarneback', 'Estimate a displacement (dx, dy) at each pixel from frame A toward frame B. Positive X moves right, positive Y down, in input-image pixels. Local quadratic fits and repeated refinement across a Gaussian pyramid resolve motion; flat areas can still produce unsupported estimates. Use reverse flow and texture checks before trusting them.', [n('levels', 'Pyramid levels', 4, 1, 6, 1), n('window', 'Window · odd pixels', 25, 5, 61, 2), n('iterations', 'Refinement iterations', 5, 1, 20, 1)], pair, [port('flow', 'field', 'Displacement field', false)]),
  spec('offsetFlow', 'Offset Flow Vectors', 'Measure', 'flow(x,y) + (dx,dy)', 'Add a constant displacement to every vector without moving its sampling positions. Restore the coarse pan after estimating residual motion, or subtract a dominant translation to inspect independent motion.', [n('dx', 'Add X · px', 0), n('dy', 'Add Y · px', 0)], [port('flow', 'field', 'Flow field')], [port('flow', 'field', 'Offset field', false)]),
  spec('flowConsistency', 'Check Reverse Flow', 'Measure', 'F(p) + B(p + F(p))', 'Follow the forward vector to the second frame, bilinearly sample the reverse vector there, and measure the distance back to the starting pixel. Reject points outside the frame or farther than the tolerance. A passing round trip is evidence, not a calibrated probability.', [n('tolerance', 'Round-trip tolerance · px', 1.5, 0, 100, 0.25)], [port('flow', 'forward', 'Forward A to B'), port('flow', 'backward', 'Backward B to A')], [port('frame', 'image', 'Valid round trips', false), port('frame', 'error', 'Return error · px', false)]),
  spec('cornerStrength', 'Corner Texture Strength', 'Measure', 'cornerMinEigenVal', 'Measure structure in two directions around each pixel. A flat patch or a single straight edge cannot uniquely determine 2D motion. Normalize by the strongest response in this frame; a uniform image remains zero. Threshold this map to reject weak evidence.', [n('block', 'Neighborhood · odd pixels', 7, 3, 31, 2)]),
  spec('flowGrid', 'Regional Median Flow', 'Measure', 'accepted vectors → cell medians', 'Divide the field into cells and take the median X/Y of accepted vectors in each. Require at least 8 accepted pixels and the chosen fraction of each cell. Rejected cells have a separate validity mask. Residual mode subtracts the median of all accepted pixels; this removes translation, not rotation or parallax.', [n('cell', 'Cell size · px', 48, 8, 512, 1), n('support', 'Minimum accepted fraction', 0.05, 0, 1, 0.01), choice('mode', 'Vector view', ['total', 'residual'])], [port('flow', 'field', 'Dense displacement'), port('frame', 'mask', 'Accepted samples')], [port('flow', 'field', 'Regional displacement', false), port('frame', 'image', 'Supported cells', false), port('scalar', 'dx', 'Dominant X · px', false), port('scalar', 'dy', 'Dominant Y · px', false), port('scalar', 'accepted', 'Accepted pixel fraction', false)]),
  spec('drawFlow', 'Draw Motion Vectors', 'Compose', 'arrowedLine · rectangle · putText', 'Draw one vector per analysis cell over the image, keeping the background at its original resolution. A smaller displacement field and its matching mask are mapped onto the background; vector lengths and dx/dy labels are converted to background-image pixels. The arrow points from A toward B; the display multiplier changes arrow length only. Gray crosses mark cells rejected by the optional validity mask. Zero motion draws a dot. Connect the same cell size used by Regional Median Flow.', [n('cell', 'Cell size · flow px', 48, 8, 512, 1), n('gain', 'Arrow display multiplier', 1, 0.1, 20, 0.1), n('background', 'Image brightness', 0.65, 0, 1, 0.05), { kind: 'boolean', key: 'grid', label: 'Show grid', default: true }, { kind: 'boolean', key: 'labels', label: 'Show dx/dy labels', default: true }], [frameIn, port('flow', 'field', 'Displacement'), { ...port('frame', 'mask', 'Validity · optional'), optional: true }]),
  spec('makeRecord', 'Make Record', 'Custom', 'Fields → named record', 'Combine typed fields into a named custom data type. Define a type in Data Types, then add its Make node.', [], [], []),
  spec('breakRecord', 'Separate Record', 'Custom', 'Named record → fields', 'Expose the fields of a named custom data type without losing their socket types.', [], [], []),
]
