import type { NodeSpec, Parameter, Port } from './types'

const number = (key: string, label: string, value: number, min: number, max: number, step = 1): Parameter => ({ kind: 'number', key, label, default: value, min, max, step })
const regions = (direction: 'in' | 'out', schema?: string): Port => ({ id: `${direction}:regions:data`, type: 'regions', label: schema ?? 'Regional data', ...(schema ? { schema } : {}) })
const stage = (type: NodeSpec['type'], title: string, description: string, input: string, output: string, parameters: Parameter[] = []): NodeSpec =>
  ({ type, title, description, category: 'Pixel layers', algorithm: 'cadence/regional pixel stages', version: 1, inputs: [regions('in', input)], outputs: [regions('out', output)], parameters })

/** Full-resolution stages: each decodes the scene's original frames on demand and keeps only compact evidence. */
export const PIXEL_CATALOG: NodeSpec[] = [
  stage('pixelCamera', 'Pixel Camera Path', 'Measure the camera between every adjacent pair at full resolution: phase correlation on a reduced copy, then robust coarse-to-fine Lucas-Kanade on luma. Pixels far from the fitted motion get no weight. The strongest motion wins, which is the camera only when it dominates the frame.', 'scene', 'pixel-camera'),
  stage('pixelRigid', 'Sliding Layers', 'Find rigid layers that slide with their own motion over the camera’s plate, such as a parallax forest: other motions measured on at least half the pairs. For each, test frames a baseline apart (12, 48 and 192 pixels of relative motion): a pixel the layer’s motion alone explains, and where the camera also fails at its destination, is paint. Paint needs Minimum own such tests, as a fraction (Own fraction) of all but the camera-only tests, and tolerates Occlusion camera-only tests each, which drawings held in front of it cause. Paint is closed, enclosed holes the camera does not explain are filled, and small pieces dropped. Pixels too few tests saw stay undecided and out of every plate. Layers are ordered by speed, as in a pan the slower plane is the farther one: a layer slower than the camera and moving its way lies behind the camera’s own plane, which then joins the list with a cover of its own, the farthest layer becoming the backdrop that is never measured. Layers are measured front to back, each tested against every other one and only where the nearer layers leave it visible.', 'pixel-camera', 'pixel-camera', [
    number('minimumOwn', 'Minimum own tests', 3, 1, 100, 1), number('ownFraction', 'Own fraction', .3, 0, 1, .01), number('occlusion', 'Occlusion', 3, 0, 20, .5),
    number('closing', 'Close radius · px', 2, 0, 8, 1), number('maximumHole', 'Largest hole filled · px', 6000, 0, 1000000, 1), number('minimumArea', 'Minimum area · px', 256, 0, 1000000, 1),
  ]),
  stage('pixelEvidence', 'Redraw Ink Evidence', 'Test every pixel of each pair against the other frame displaced by the camera. A pixel is explained when its value lies between the minimum and maximum of the other frame sampled within Reach pixels, so a new resampling phase of the same drawing passes while a redrawn line fails. Changed pixels are stored in world coordinates with an ink sign: ink arrives when the later frame is darker and locally dark (a line), leaves when the earlier one is.', 'pixel-camera', 'pixel-evidence', [
    number('reach', 'Reach · px', .5, 0, 2, .05), number('noiseFactor', 'Noise factor', 4, .5, 20, .1), number('gradientSlope', 'Edge tolerance per gradient code', .1, 0, 2, .01),
    number('inkDelta', 'Ink contrast · codes', 8, 0, 128, 1), number('lineDelta', 'Line darkness · codes', 4, 0, 64, 1), number('dilation', 'Change dilation · px', 1, 0, 4, 1),
  ]),
  stage('pixelScenery', 'Scenery Median', 'Take the median luma of every world pixel that ever changed, over the whole shot, and mark each change whose value before or after it is that scenery (within Tolerance codes, from at least Minimum samples). Drawing Silhouettes then rejects ink revealed from under a drawing that is the scenery, unless the change only boiled (the same structure within 2 pixels). A drawing passing over a pixel is a minority of its history; one that stands still boils in place.', 'pixel-evidence', 'pixel-evidence', [
    number('tolerance', 'Tolerance · codes', 10, 0, 64, 1), number('minimumSamples', 'Minimum samples', 8, 1, 255, 1),
  ]),
  stage('pixelSilhouettes', 'Drawing Silhouettes', 'For every frame, take the ink of the drawing held at that frame: ink that arrived at each pixel’s last change before it, or leaves at its next change after it. Close the ink, fill enclosed holes and drop small components. Artwork that never changes stays in the scenery; background a drawing vacates or is about to cover carries the opposite ink sign. Ink whose value recurs before the previous change or after the next one, within Recurrence codes, is scenery a drawing covered and uncovered (0 disables). Leaving ink whose value is the scenery median and did not boil can be dropped: recurring (the value comes back at another time), known (the pixel never changed before, or its last change revealed the scenery), always; and whenever its change is at least Leave horizon frames away (0 disables). With a Hold tolerance, held ink must still show the value its bracket measured, within that many codes of the frame’s 3x3 range: a mark that fades in below the change threshold and then vanishes has a single change, and is not ink in the frames long before it.', 'pixel-evidence', 'pixel-silhouettes', [
    number('closeRadius', 'Close radius · px', 6, 0, 32, 1), number('minimumArea', 'Minimum area · px', 800, 1, 1000000, 1), number('erode', 'Erode · px', 0, 0, 8, 1), number('recurrence', 'Recurrence · codes', 0, 0, 64, 1), { kind: 'select', key: 'sceneryLeaves', label: 'Scenery about to be covered', default: 'never', options: ['never', 'recurring', 'known', 'always'] }, number('leaveHorizon', 'Leave horizon · frames', 0, 0, 1000, 1), number('holdTolerance', 'Hold tolerance · codes · 0 = off', 12, 0, 255, 1),
  ]),
  stage('pixelPlate', 'Background Plate', 'Accumulate every frame outside its silhouettes, grown by Margin, into a world atlas. Pixels only another rigid layer explains (a sliding background) stay out. A plain mean first, then the mean of samples within three spreads of it (never under Floor codes). Pixels never seen outside a drawing stay unknown. Then each frame gets a drift: per cell of Drift cell pixels, the median of the frame minus the plate outside the drawings, so lighting that changes over the shot (a fade, a darkening sky) is followed; 0 disables it. Sliding layers get their own plate outside the drawings and the layers in front of them, back to front, and their rim a matte: a layer pixel slides over changing scenery, so least squares over the frames gives its alpha and premultiplied color against what lies behind it, the camera plate or the farther layers. With a backdrop no pixel shows the camera plate, which stays empty.', 'pixel-silhouettes', 'pixel-plate', [
    number('margin', 'Margin · px', 3, 0, 16, 1), number('floor', 'Floor · codes', 4, 0, 64, .5), number('drift', 'Drift cell · px', 64, 0, 1024, 1),
  ]),
  stage('pixelRefine', 'Refine Silhouettes', 'Carve silhouette pixels the plate explains, from the outside in: within Band pixels of the edge, a pixel matching a plate observed at least Minimum count times (every channel within Tolerance codes, plus a gradient allowance) is background when it connects to the exterior through such pixels. The outline, which does not match the scenery, stops the carve, and interior fills that happen to match it are never reached. Rebuild the plate afterwards with a second Background Plate.', 'pixel-plate', 'pixel-silhouettes', [
    number('band', 'Band · px', 8, 0, 64, 1), number('tolerance', 'Tolerance · codes', 6, 0, 64, .5), number('minimumCount', 'Minimum count', 3, 1, 1000, 1),
  ]),
  stage('pixelRigidRefine', 'Sliding Layers, Second Pass', 'With the drawings known, measure every sliding layer’s cover again while skipping pixels a drawing covers in either frame of a test, where only occlusion could be measured. Then drop cover what lies behind explains in at least half the frames it is known (every channel within Tolerance codes), the camera plate or the farther layers: a narrow gap of smooth scenery between two pieces of paint holds still in the layer’s coordinates, yet shows what is behind. With planes behind the camera’s own, smooth paint no test decided (the inside of a trunk wider than every test shift) is claimed where it holds still in the layer’s coordinates, 70% of the frames that saw it match its trimmed mean, what lies behind misses it by 6 codes more, and it connects to the cover. Rebuild both plates and carve the silhouettes against the new scene. Passes its input through when no sliding layer was found.', 'pixel-silhouettes', 'pixel-silhouettes', [
    number('band', 'Band · px', 8, 0, 64, 1), number('tolerance', 'Tolerance · codes', 6, 0, 64, .5), number('minimumCount', 'Minimum count', 3, 1, 1000, 1),
  ]),
  stage('pixelGrow', 'Grow Silhouettes', 'Add to each silhouette the pixels beside it that the scene cannot explain: a part of a drawing that never changed carries no ink, and the plate behind it, seen as that part in some frames and as scenery in others, matches neither. Growth floods from the silhouette’s edge through pixels that differ from the scene by over Tolerance codes (plus a gradient allowance), within Band pixels of it and only inside its concavities (its closing by Bay pixels): scenery beside a drawing that stands there later disagrees with a plate that remembers it too. Rebuild the plate afterwards with another Background Plate.', 'pixel-plate', 'pixel-silhouettes', [
    number('band', 'Band · px', 24, 0, 128, 1), number('bay', 'Bay · px', 48, 0, 256, 1), number('tolerance', 'Tolerance · codes', 16, 0, 128, .5),
  ]),
  stage('pixelFrames', 'Layer Frames', 'Link silhouette components through time by their overlap in world coordinates; everything that ever touches becomes one layer. Split each layer into held drawings at every pair whose changes inside it reach Minimum changes and Minimum fraction of its area. Each drawing keeps a thumbnail cut from its first frame.', 'pixel-plate', 'pixel-frames', [
    number('minimumChanges', 'Minimum changes · px', 60, 1, 1000000, 1), number('minimumFraction', 'Minimum fraction of layer', .06, 0, 1, .005),
  ]),
  { type: 'pixelInspect', title: 'Inspect Pixel Layers', category: 'Pixel layers', algorithm: 'Read-only full-resolution panels', version: 1,
    description: 'Show one source frame with the pixel stages computed so far. Changes: this frame to the next, green where ink arrives, magenta where it leaves, yellow for other changes. Ink: the held drawing’s ink with its silhouette outline in cyan. Layer: silhouette pixels over a checkerboard, with the edge unmixed against the plate where it is known (straight alpha). Plate: the background at this camera position, with any sliding layer over it where it paints (outlined in green), unknown in purple, disagreement outside the silhouettes in orange (over 12 codes) and red (over 20). Planes: each sliding plane alone at this frame, back to front, straight alpha over a checkerboard, unknown in purple; with planes behind the camera these are the backdrop, the planes between and the camera’s own plane, and together they are the whole scene. Rebuilt: the frame from the layers alone, the scene with each shown drawing assembled once over its whole hold (the frames agreeing with the median alpha, averaged on the world grid) and carried by the camera; its residual is dim where right, green inside a drawing, orange over 6 codes, red over 12. Layer frames: every held drawing of the layers on screen, the one shown now outlined.',
    inputs: [regions('in')], outputs: [
      { id: 'out:frame:source', label: 'Source', type: 'frame' }, { id: 'out:frame:changes', label: 'Changes to next', type: 'frame' },
      { id: 'out:frame:ink', label: 'Held ink', type: 'frame' }, { id: 'out:frame:layer', label: 'Layer', type: 'frame' },
      { id: 'out:frame:plate', label: 'Plate', type: 'frame' }, { id: 'out:frame:planes', label: 'Planes', type: 'frame' }, { id: 'out:frame:rebuilt', label: 'Rebuilt from layers', type: 'frame' }, { id: 'out:frame:residual', label: 'Rebuilt residual', type: 'frame' },
      { id: 'out:frame:drawings', label: 'Layer frames', type: 'frame' }, { id: 'out:string:summary', label: 'Summary', type: 'string' },
    ], parameters: [number('frame', 'Source frame', 0, 0, 1000000000), number('displayMaxSide', 'Display max side · 0 = full', 960, 0, 3840)] },
]
