import type { NodeSpec, Parameter, Port } from './types'

const number = (key: string, label: string, value: number, min: number, max: number, step = 1): Parameter => ({ kind: 'number', key, label, default: value, min, max, step })
const regions = (direction: 'in' | 'out', schema?: string): Port => ({ id: `${direction}:regions:data`, type: 'regions', label: schema ?? 'Regional data', ...(schema ? { schema } : {}) })
const stage = (type: NodeSpec['type'], title: string, description: string, input: string, output: string, parameters: Parameter[] = [], version = 1): NodeSpec => ({ type, title, description, category: 'Regional analysis', algorithm: 'cadence/regional', version, inputs: [regions('in', input)], outputs: [regions('out', output)], parameters })

/** Whole-scene data stays explicit; only inspector nodes depend on timeline time. */
export const REGIONAL_CATALOG: NodeSpec[] = [
  { type: 'sceneRange', title: 'Scene Range', category: 'Regional analysis', description: 'Decode an inclusive, contiguous source range once. The range must contain one shot. Original pixels remain in the video; these BGR8 images are analysis-only.', algorithm: 'WebCodecs -> BGR8 -> INTER_AREA', version: 1,
    inputs: [{ id: 'in:video:clip', label: 'Video clip', type: 'video' }], outputs: [regions('out', 'scene')],
    parameters: [number('first', 'First frame', 0, 0, 1000000000), number('last', 'Last frame (inclusive)', 23, 1, 1000000000), number('maxSide', 'Analysis max side', 320, 96, 640)] },
  stage('regionalMotion', 'Scene Dense Motion', 'Forward and backward optical flow across every adjacent pair, with texture, round-trip and observed-border validity. Invalid measurements remain unknown.', 'scene', 'motion', [number('window', 'Flow window', 25, 9, 61), number('levels', 'Pyramid levels', 4, 1, 6), number('roundTrip', 'Round-trip limit', 1.5, .1, 8, .1)]),
  stage('regionalPool', 'Multiscale Motion Cells', 'Pool the same accepted dense field at 96, 48, 24, 12 and 8 pixels. These are alternate summaries, not independent votes. Mixed cells remain marked incoherent.', 'motion', 'pooled'),
  stage('regionalTracks', 'Whole-Scene Motion Groups', 'Advect support cells and group compatible overlapping motion histories. Groups are motion evidence, not object identities or pixel silhouettes.', 'pooled', 'tracks', [number('tolerance', 'Motion tolerance', .75, .1, 4, .05), number('minimumOverlap', 'Minimum pair overlap', 4, 2, 30)]),
  stage('regionalHistory', 'Motion-History Grouping', 'Join disconnected regions whose measured velocities agree at matching times throughout the scene. Compatible proposals are ordered only by motion evidence, not spatial proximity. Original regions and drawing events are preserved.', 'tracks', 'history', [number('tolerance', 'Velocity tolerance', .75, .1, 4, .05), number('minimumOverlap', 'Minimum shared pairs', 4, 2, 30)], 3),
  stage('regionalTiming', 'Regional Drawing Events', 'Compare supported appearance after one fitted regional translation. Report held, changed or unknown without deforming the drawings or assuming an on-2s/on-3s cadence.', 'tracks', 'timing'),
  stage('regionalComplete', 'Support Completion', 'Associate nearby coherent motion using independent neighboring-frame evidence, then infer bounded support gaps around original same-family seeds. Optional isolated-hole and temporal-hole cleanup retain separate provenance. Temporal gaps need bracketing aligned donors, or two future witnesses at the true scene start. Contradictory motion and competing families veto filling. Inferred support never changes original motion, grouping or drawing events; this is not a silhouette or recovered artwork.', 'history', 'completion', [number('maxHoleDistance', 'Max hole distance (cells)', 6, 0, 32), number('maxBorderDistance', 'Max border distance (cells)', 6, 0, 32), number('competitorClearance', 'Competitor clearance (cells)', 2, 0, 32), { kind: 'boolean', key: 'fillIsolated', label: 'Fill isolated holes', default: true }, { kind: 'boolean', key: 'bridgeTemporal', label: 'Bridge temporal holes', default: true }], 5),
  { type: 'regionalInspect', title: 'Inspect Regional Evidence', category: 'Regional analysis', description: 'Inspect an absolute source frame with original-video detail beneath cached analysis evidence. Display max side controls each panel independently of analysis; 0 uses analysis pixels. The final source frame has no outgoing motion pair. Colored support is not a recovered layer silhouette.', algorithm: 'Read-only diagnostic raster', version: 6,
    inputs: [regions('in')], outputs: [{ id: 'out:frame:image', label: 'Diagnostic image', type: 'frame' }, { id: 'out:string:summary', label: 'Evidence summary', type: 'string' }],
    parameters: [number('frame', 'Source frame', 0, 0, 1000000000), { kind: 'select', key: 'view', label: 'View', default: 'review', options: ['source', 'flow', 'validity', 'cells', 'tracks', 'families', 'velocities', 'conflicts', 'completion', 'events', 'timeline', 'review'] }, { kind: 'select', key: 'cellSize', label: 'Cell size', default: '24', options: ['96', '48', '24', '12', '8'] }, number('groupPage', 'Group page', 0, 0, 100000), number('displayMaxSide', 'Display max side', 960, 0, 1280)] },
  { type: 'regionalCompletionInspect', title: 'Inspect Support Completion', category: 'Regional analysis', description: 'Expose source, measured family support, completed support and inference provenance as independent frames. Display max side applies to each frame; 0 uses analysis pixels. Inferred support is not a recovered layer silhouette. Use Frame Layout to arrange a comparison.', algorithm: 'Read-only diagnostic panels', version: 1,
    inputs: [regions('in', 'completion')], outputs: [
      { id: 'out:frame:source', label: 'Source', type: 'frame' }, { id: 'out:frame:measured', label: 'Measured support', type: 'frame' },
      { id: 'out:frame:completed', label: 'Completed support', type: 'frame' }, { id: 'out:frame:provenance', label: 'Inference provenance', type: 'frame' },
      { id: 'out:string:summary', label: 'Evidence summary', type: 'string' },
    ], parameters: [number('frame', 'Source frame', 0, 0, 1000000000), number('displayMaxSide', 'Display max side', 960, 0, 1280)] },
]
