import type { NodeSpec, Parameter, Port } from './types'

const number = (key: string, label: string, value: number, min: number, max: number, step = 1): Parameter => ({ kind: 'number', key, label, default: value, min, max, step })
const regions = (direction: 'in' | 'out', schema?: string): Port => ({ id: `${direction}:regions:data`, type: 'regions', label: schema ?? 'Regional data', ...(schema ? { schema } : {}) })
const stage = (type: NodeSpec['type'], title: string, description: string, input: string, output: string, parameters: Parameter[] = [], version = 1): NodeSpec => ({ type, title, description, category: 'Regional analysis', algorithm: 'cadence/regional', version, inputs: [regions('in', input)], outputs: [regions('out', output)], parameters })

/** Whole-scene data stays explicit; only inspector nodes depend on timeline time. */
export const REGIONAL_CATALOG: NodeSpec[] = [
  stage('vectorCandidates', 'Scene Vector Candidates', 'Use the Regional motion vectors estimator across a scene: phase-correlation pan, forward/backward Farneback, fixed relative texture and round-trip checks, then cell medians. Verify border vectors compares disconnected eight-connected border components against observed source pixels before grouping. Any coherent interior witness protects its own component, not distant edge patches sharing its velocity. A sharp-outline fallback can compare observed-only 5x5 float descriptors after the raw visibility, relative-improvement and context checks pass. This filters analysis evidence, never source/display pixels. Raw dense flow, original cell vectors and correction evidence remain available. Grouping freezes the original assignments and transfers only verified cells to the existing background group; unrelated IDs and models are not recomputed. Corrections are rejected for the whole pair if they cannot retain those assignments in the approved coarse/default configurations. Disable verification for the original pooled vectors. Filling controls are downstream and do not disable verification or change raw groups. Mixed cells remain candidates with separate confidence. No temporal filtering or support completion.', 'scene', 'vector-candidates', [number('cellSize', 'Cell size', 8, 8, 96), number('window', 'Flow window', 25, 9, 61), number('levels', 'Pyramid levels', 4, 1, 6), number('roundTrip', 'Round-trip limit', 1.5, .1, 8, .1), number('textureFraction', 'Relative texture threshold', .005, .0001, 1, .001), { kind: 'boolean', key: 'verifyBorders', label: 'Verify border vectors', default: true }], 5),
  stage('vectorGroups', 'Frame Velocity Groups', 'Group every available candidate by velocity within each frame. Maximum velocity radius bounds the initial grouping; optional subtle-motion separation uses measured variation around the dominant tight motion to retain smaller differences. Interior witnesses must support a subtle split; reflected-border estimates alone cannot create one. Separate distant regions can divide non-dominant groups using a loose cell gap while keeping the dominant background group unchanged. Split regions retain their parent motion vector. Verified border corrections transfer only listed cells from their original assignments; unaffected IDs and models remain frozen, so IDs can have gaps. Custom tighter radii retain a corrected vector as its own group if it cannot fit the original background model. Velocities are recomputed per pair, allowing acceleration, easing and reversal. Mixed measurements retain their own confidence but are never removed by temporal history, minimum group size or ambiguity. IDs and colors are frame-local proposals, not tracked artwork identities. Missing vectors stay unknown.', 'vector-candidates', 'vector-groups', [number('tolerance', 'Maximum velocity radius', .75, .1, 4, .05), { kind: 'boolean', key: 'splitSubtleMotion', label: 'Separate subtle motion', default: true }, { kind: 'boolean', key: 'splitDistantRegions', label: 'Separate distant regions', default: true }, number('proximityGap', 'Foreground gap (cells)', 4, 0, 16)], 7),
  { type: 'vectorInspect', title: 'Inspect Direct Motion', category: 'Regional analysis', description: 'Expose source, candidate vectors, frame-local motion groups and confidence as four independent frames. All available candidates receive a group; confidence does not remove cells. Display resolution is independent of analysis; colored cells are motion proposals, not silhouettes or persistent identities.', algorithm: 'Read-only direct-motion panels', version: 2,
    inputs: [regions('in')], outputs: [
      { id: 'out:frame:source', label: 'Source', type: 'frame' }, { id: 'out:frame:candidates', label: 'Candidate vectors', type: 'frame' },
      { id: 'out:frame:groups', label: 'Motion groups', type: 'frame' }, { id: 'out:frame:confidence', label: 'Confidence', type: 'frame' },
      { id: 'out:string:summary', label: 'Evidence summary', type: 'string' },
    ], parameters: [number('frame', 'Source frame', 0, 0, 1000000000), number('gain', 'Vector display gain', 3, .1, 20, .1), number('displayMaxSide', 'Display max side', 960, 0, 1280)] },
  stage('vectorTrack', 'Track Motion Identities', 'Associate measured frame-local groups with persistent scene track IDs without changing groups, vectors, confidence or support. Dominant group zero keeps track zero; this is not semantic background classification. Foreground matches use predicted spatial support and one-to-one assignment; absent tracks may remain dormant for Max gap pairs. Match radius is measured in analysis cells. A dormant track can recover its color when observed again, but no foreground mask is invented on held frames that measure only background.', 'vector-groups', 'vector-identities', [number('maxGap', 'Max gap (pairs)', 24, 0, 120), number('matchRadius', 'Match radius (cells)', 3, 0, 16, .25)]),
  stage('vectorComplete', 'Complete Direct Support', 'Infer missing support, edges first and enclosed holes second. Preserve every assignment from the existing 75-percent measured-edge rule and bounded inward-ray or winding-pocket rule. Extend only their remaining unknown cells: each actual frame edge keeps a 75-percent measured majority, or otherwise chooses its largest original measured touching group. Newly resolvable corner conflicts use original frame-wide measured size, then lowest ID; they cannot overwrite an existing edge assignment. Measured cells stay unchanged, and filled cells never become edge anchors or increase group sizes. Edges without measured anchors receive no new full-edge proposal. After edges are resolved, repeatedly fill enclosed eight-connected holes with their largest touching group using original measured size and lowest-ID ties. Unrelated groups and holes open to the frame do not qualify. Repeat until no cells change. Additions record edge or enclosed-hole inference, never new vectors or confidence. Reach zero disables all edge filling; positive reach bounds only the inward fallback, not the full-edge span. This is support inference, not recovered pixels or a pixel-accurate silhouette.', 'vector-groups', 'vector-completion', [{ kind: 'boolean', key: 'fillHoles', label: 'Fill enclosed holes', default: true }, { kind: 'boolean', key: 'fillEdges', label: 'Extend to edges', default: true }, number('edgeReach', 'Edge reach (cells)', 8, 0, 32)], 8),
  { type: 'vectorCompletionInspect', title: 'Inspect Direct Completion', category: 'Regional analysis', description: 'Expose source, measured groups, completed support and inference provenance as independent frames. Filled cells are inferred support, never measured vectors. Original group colors and measured opacity are retained; display resolution is independent of analysis.', algorithm: 'Read-only direct-completion panels', version: 1,
    inputs: [regions('in', 'vector-completion')], outputs: [
      { id: 'out:frame:source', label: 'Source', type: 'frame' }, { id: 'out:frame:measured', label: 'Measured groups', type: 'frame' },
      { id: 'out:frame:completed', label: 'Completed support', type: 'frame' }, { id: 'out:frame:provenance', label: 'Inference provenance', type: 'frame' },
      { id: 'out:string:summary', label: 'Evidence summary', type: 'string' },
    ], parameters: [number('frame', 'Source frame', 0, 0, 1000000000), number('displayMaxSide', 'Display max side', 960, 0, 1280)] },
  stage('vectorFragments', 'Merge Transient Fragments', 'Infer membership for small short-lived foreground components from the surrounding support and temporal evidence. Partial enclosure requires measured host-or-dominant support on at least half the boundary and at least twice as many host boundary cells as dominant-group boundary cells. Unknown boundary cells abstain and never count as measured coverage. This downstream stage does not change measured groups, motion, confidence, completed support or identity associations. Its separate per-cell track labels affect only the final tracked completed panel; merged cells receive pink provenance. Disable Enabled for the original tracked support. Unknown cells and dominant group zero remain unchanged. This is inferred membership, not recovered artwork or a pixel-accurate silhouette.', 'vector-completion', 'vector-fragments', [{ kind: 'boolean', key: 'enabled', label: 'Enabled', default: true }], 3),
  { type: 'vectorIdentityInspect', title: 'Inspect Tracked Support', category: 'Regional analysis', description: 'Color approved measured and completed support by persistent track ID. Source, measured support and confidence opacity remain unchanged by fragment merging. When Merge Transient Fragments is connected and enabled, only completed track membership changes, with pink provenance on each merged cell. Disable Stable colors to bypass both identity colors and fragment merges for the exact frame-local view. Held background-only frames remain background; dormant tracks do not create character masks.', algorithm: 'Read-only tracked-support panels', version: 2,
    inputs: [regions('in', 'vector-completion')], outputs: [
      { id: 'out:frame:source', label: 'Source', type: 'frame' }, { id: 'out:frame:measured', label: 'Measured groups', type: 'frame' },
      { id: 'out:frame:completed', label: 'Completed support', type: 'frame' }, { id: 'out:frame:provenance', label: 'Inference provenance', type: 'frame' },
      { id: 'out:string:summary', label: 'Identity summary', type: 'string' },
    ], parameters: [number('frame', 'Source frame', 0, 0, 1000000000), { kind: 'boolean', key: 'stableColors', label: 'Stable colors', default: true }, number('displayMaxSide', 'Display max side', 960, 0, 1280)] },
  { type: 'sceneRange', title: 'Scene Range', category: 'Regional analysis', description: 'Decode an inclusive, contiguous source range once. The range must contain one shot. Original pixels remain in the video; these BGR8 images are analysis-only.', algorithm: 'WebCodecs -> BGR8 -> INTER_AREA', version: 1,
    inputs: [{ id: 'in:video:clip', label: 'Video clip', type: 'video' }], outputs: [regions('out', 'scene')],
    parameters: [number('first', 'First frame', 0, 0, 1000000000), number('last', 'Last frame (inclusive)', 23, 1, 1000000000), number('maxSide', 'Analysis max side', 320, 96, 640)] },
  stage('regionalMotion', 'Scene Dense Motion', 'Forward and backward optical flow across every adjacent pair, with texture, round-trip and observed-border validity. Invalid measurements remain unknown.', 'scene', 'motion', [number('window', 'Flow window', 25, 9, 61), number('levels', 'Pyramid levels', 4, 1, 6), number('roundTrip', 'Round-trip limit', 1.5, .1, 8, .1)]),
  stage('regionalPool', 'Multiscale Motion Cells', 'Pool the same accepted dense field at 96, 48, 24, 12 and 8 pixels. These are alternate summaries, not independent votes. Mixed cells remain marked incoherent.', 'motion', 'pooled'),
  stage('regionalTracks', 'Whole-Scene Motion Groups', 'Advect support cells and group compatible overlapping motion histories. Groups are motion evidence, not object identities or pixel silhouettes.', 'pooled', 'tracks', [number('tolerance', 'Motion tolerance', .75, .1, 4, .05), number('minimumOverlap', 'Minimum pair overlap', 4, 2, 30)]),
  stage('regionalHistory', 'Motion-History Grouping', 'Join disconnected regions whose measured velocities agree at matching times throughout the scene. Compatible proposals are ordered only by motion evidence, not spatial proximity. Original regions and drawing events are preserved.', 'tracks', 'history', [number('tolerance', 'Velocity tolerance', .75, .1, 4, .05), number('minimumOverlap', 'Minimum shared pairs', 4, 2, 30)], 3),
  stage('regionalTiming', 'Regional Drawing Events', 'Compare supported appearance after one fitted regional translation. Report held, changed or unknown without deforming the drawings or assuming an on-2s/on-3s cadence.', 'tracks', 'timing'),
  stage('regionalComplete', 'Support Completion', 'Associate nearby coherent motion using independent neighboring-frame evidence, then infer bounded support gaps around original same-family seeds. Optional isolated-hole and temporal-hole cleanup retain separate provenance. Temporal gaps need bracketing full-footprint donors, or two witnesses toward the scene interior at a verified scene boundary. A bounded border pass uses frozen temporal anchors. Final cleanup can close fully enclosed narrow pockets of at most four cells or one compatible coherent cell, retaining motion and competing-family guards. These additions never become donors. Clipped support never counts as a donor; contradictory motion, competing families and viewport re-entry veto filling. Inferred support never changes original motion, grouping or drawing events; this is not a silhouette or recovered artwork.', 'history', 'completion', [number('maxHoleDistance', 'Max hole distance (cells)', 6, 0, 32), number('maxBorderDistance', 'Max border distance (cells)', 6, 0, 32), number('competitorClearance', 'Competitor clearance (cells)', 2, 0, 32), { kind: 'boolean', key: 'fillIsolated', label: 'Fill isolated holes', default: true }, { kind: 'boolean', key: 'bridgeTemporal', label: 'Bridge temporal holes', default: true }], 8),
  { type: 'regionalInspect', title: 'Inspect Regional Evidence', category: 'Regional analysis', description: 'Inspect an absolute source frame with original-video detail beneath cached analysis evidence. Display max side controls each panel independently of analysis; 0 uses analysis pixels. The final source frame has no outgoing motion pair. Colored support is not a recovered layer silhouette.', algorithm: 'Read-only diagnostic raster', version: 6,
    inputs: [regions('in')], outputs: [{ id: 'out:frame:image', label: 'Diagnostic image', type: 'frame' }, { id: 'out:string:summary', label: 'Evidence summary', type: 'string' }],
    parameters: [number('frame', 'Source frame', 0, 0, 1000000000), { kind: 'select', key: 'view', label: 'View', default: 'review', options: ['source', 'flow', 'validity', 'cells', 'tracks', 'families', 'velocities', 'conflicts', 'completion', 'events', 'timeline', 'review'] }, { kind: 'select', key: 'cellSize', label: 'Cell size', default: '24', options: ['96', '48', '24', '12', '8'] }, number('groupPage', 'Group page', 0, 0, 100000), number('displayMaxSide', 'Display max side', 960, 0, 1280)] },
  { type: 'regionalCompletionInspect', title: 'Inspect Support Completion', category: 'Regional analysis', description: 'Expose source, measured family support, completed support and inference provenance as independent frames. Display max side applies to each frame; 0 uses analysis pixels. Inferred support is not a recovered layer silhouette. Use Frame Layout to arrange a comparison.', algorithm: 'Read-only diagnostic panels', version: 1,
    inputs: [regions('in', 'completion')], outputs: [
      { id: 'out:frame:source', label: 'Source', type: 'frame' }, { id: 'out:frame:measured', label: 'Measured support', type: 'frame' },
      { id: 'out:frame:completed', label: 'Completed support', type: 'frame' }, { id: 'out:frame:provenance', label: 'Inference provenance', type: 'frame' },
      { id: 'out:string:summary', label: 'Evidence summary', type: 'string' },
    ], parameters: [number('frame', 'Source frame', 0, 0, 1000000000), number('displayMaxSide', 'Display max side', 960, 0, 1280)] },
]
