import { useEffect, useMemo, useRef, useState } from 'react'
import { Global } from '@emotion/react'
import { topological } from '../engine/graph'
import { explicitGraph } from '../engine/prefabs'
import type { Prefab } from '../engine/prefabs'
import { PORT_COLORS, PORT_LABELS, specFor } from '../engine/specs'
import { GENERATED_FPS, outputCount } from '../engine/time'
import { bake, cancel, inspect, loadVideo, saveBlob, refreshThumbnails, openProjectFolder } from './client'
import { computationKey, useEditor } from './store'
import { EditorTabs } from './EditorTabs'
import { Graph } from './Graph'
import { Preview } from './Preview'
import { TimelineSlider } from './TimelineSlider'
import { usePreviewShortcuts } from './usePreviewShortcuts'
import { ThemeSelect } from './ThemeSelect'
import { FramePlayer } from './FramePlayer'
import type { FramePlayerHandle } from './FramePlayer'
import { saveGraph, syncProject, supportsProjectFolder, useWorkspace, ensureProjectFolder } from './workspace'
import { styles } from './styles'

const explanations: Partial<Record<import('../engine/types').NodeType, string[]>> = {
  groupInput: ['Expose the inputs supplied to this custom-node instance by its parent graph.', 'Choose a socket in the inspector to see a specific input. Unconnected number, boolean and text inputs use that instance’s fallback value. The interface panel controls port names and types.'],
  groupOutput: ['Forward the internal results connected to these sockets to the parent graph.', 'Each socket becomes a selectable output on every instance of this custom node. Add or rename sockets in the interface panel, then wire the result you want to expose.'],
  source: ['Read the clip’s presentation index, find a preceding keyframe, and decode forward to this exact image.', 'A fractional time still reads its earlier whole source frame. Frame generation happens downstream. The clip’s audio is not processed.'],
  grayscale: ['Multiply each RGB pixel by the selected channel weights and sum them into brightness.', 'Removing color lets later steps compare structure. Rec.709 gives green more weight because it contributes more to perceived brightness.'],
  blur: ['Place a Gaussian kernel over each pixel, weight its neighbors, and sum them into a new value.', 'A small blur reduces grain that would otherwise look like motion in Frame Delta. Radius controls the neighborhood; sigma controls how quickly the weights fall off.'],
  delta: ['Request frame N from branch A and N + offset from branch B. Subtract their corresponding pixels, after running both upstream chains.', 'Bright absolute differences show what changed, including camera motion, moving characters and lighting. They are evidence of change, not an object mask. Mean |Δ luma| summarizes brightness change as one number.'],
  motion: ['Convert both inputs to grayscale and soften their borders with a Hann window. Phase correlation compares their Fourier phases; the location of the correlation peak gives the X/Y translation.', 'One vector describes the entire image. Repeating it as enlarged arrows makes direction visible. Independent character movement, cuts and parallax can invalidate this camera estimate; the response is a diagnostic, not a probability.'],
  translateX: ['Shift each pixel horizontally using a translation matrix and bilinear spatial sampling.', 'Connect a number to drive displacement, or use the fallback X value. Positive values move right. Newly exposed pixels are black because their contents are unknown.'],
  translateY: ['Shift each pixel vertically using a translation matrix and bilinear spatial sampling.', 'Connect a number to drive displacement, or use the fallback Y value. Positive values move down. Compose this with Translate X to build your own Translate utility.'],
  multiply: ['Multiply A by B. A connected B input overrides the fallback value.', 'For example, estimated Δx × time fraction gives the horizontal displacement at an intermediate instant. This keeps the interpolation calculation visible in your graph.'],
  constant: ['Supply one editable number to any compatible input.', 'Reuse the same value across branches, expose it through a custom-node interface, or multiply it by time to animate a transform.'],
  time: ['Split the requested source-frame time into its integer part and fractional remainder. At frame 12.4, the fraction output is 0.4.', 'Multiply a displacement by this fraction, then connect the result to Translate X or Translate Y. During a 60 fps render, each output timestamp requests a new fraction. No interpolation method is hidden in this node.'],
  extractFrame: ['Evaluate the connected upstream branch at exactly frame N, then keep that result as the timeline moves. Frame numbering starts at 0.', 'Connect Video Source to two Extract Frame nodes, choose their frame indices, and connect their outputs to A and B of Frame Delta. A downstream B offset does not change either pinned frame. Filters before extraction are also evaluated at N; upstream Frame Offset nodes still apply their own offsets.'],
  offset: ['Add a whole-frame offset to the time requested from every node upstream of this input.', 'Use this to access another source drawing anywhere in your graph. The preview shows the resulting shifted branch, while the main timeline remains at the original evaluation time.'],
  threshold: ['Convert brightness to a single channel, compare it with the cutoff, and output white for selected pixels and black for everything else.', 'Use this on Frame Delta to isolate changed areas, then inspect and refine the mask. A difference mask only marks changed pixels; it does not establish layer ownership or recover hidden background.'],
  composite: ['Start with the background. Wherever mask brightness is greater than 0.5, replace that pixel with the corresponding foreground pixel.', 'This is a hard mask, with no temporal blending. Warp the mask and foreground together when moving a layer. All three inputs must have matching dimensions.'],

  output: ['Forward the connected image as the graph’s final result. Right-click any earlier node and choose Select for preview to inspect how the frame was made.', 'Render evaluates this graph at each output timestamp, encodes the resulting frames, and joins them into a silent MP4. A filter-only graph holds source frames; Time-driven transforms can create intermediate positions.'],
}

export const App = () => {
  const projectFolder = useWorkspace()
  const [examples, setExamples] = useState<string[]>([])
  useEffect(() => { let active = true; void fetch(`${import.meta.env.BASE_URL}samples.json`).then(response => response.json()).then(names => { if (active && Array.isArray(names)) setExamples(names.filter(name => typeof name === 'string')) }).catch(() => {}); return () => { active = false } }, [])
  const state = useEditor(), { doc, view, selected, port, frame, source, ready, busy, result } = state
  const [preset, setPreset] = useState<Prefab>('difference'), [sample, setSample] = useState(''), [start, setStart] = useState(0), [end, setEnd] = useState(0), [fps, setFps] = useState(60), [left, setLeft] = useState(52), [showInfo, setShowInfo] = useState(false), [pane, setPane] = useState<'graph' | 'preview'>('graph'), [renderTarget, setRenderTarget] = useState('n5')
  const inspector = state.inspectorView, setInspector = (inspectorView: 'frame' | 'movie') => useEditor.setState({ inspectorView })
  const moviePlayer = useRef<FramePlayerHandle>(null)
  usePreviewShortcuts(moviePlayer)
  const videoInput = useRef<HTMLInputElement>(null), projectInput = useRef<HTMLInputElement>(null), prefabInput = useRef<HTMLInputElement>(null), workspace = useRef<HTMLDivElement>(null)
  const locked = busy === 'bake' || busy === 'load', key = computationKey(doc)
  const frameCount = source?.frameCount ?? state.generatedFrames, timelineFps = source?.fps ?? GENERATED_FPS
  const node = view.nodes.find(n => n.id === selected), spec = node && specFor(node, view), outputs = spec ? node?.type === 'groupOutput' ? spec.inputs : spec.outputs : []
  const flow = useMemo(() => topological(view), [view])
  const inspectionContext = JSON.stringify([key, selected, port, state.gain, source?.id, state.activeTab, state.revision]), inspectionIdentity = JSON.stringify([inspectionContext, frame])
  const lastInspection = useRef(''), lastInspectionContext = useRef(''), lastInspectionTime = useRef(0)
  useEffect(() => {
    if (!ready || locked || state.fatal || lastInspection.current === inspectionIdentity) return
    // Finish the current frame, then seek straight to the newest pointer position.
    // Graph/target edits still cancel stale work, but rapid seeks cannot starve the preview.
    if (busy === 'inspect' && lastInspectionContext.current === inspectionContext) return
    // Throttle instead of debouncing: continuous scrubbing must still produce previews.
    const timer = setTimeout(() => {
      lastInspection.current = inspectionIdentity; lastInspectionContext.current = inspectionContext
      lastInspectionTime.current = performance.now(); inspect()
    }, Math.max(0, 80 - (performance.now() - lastInspectionTime.current)))
    return () => clearTimeout(timer)
  }, [inspectionIdentity, ready, locked, busy])
  const enabledPreviews = JSON.stringify(state.previews)
  useEffect(() => { if (busy !== 'idle') return; const timer = setTimeout(refreshThumbnails, 150); return () => clearTimeout(timer) }, [busy, enabledPreviews, key, frame, state.gain, source?.id, state.activeTab])
  useEffect(() => { if (!doc.nodes.some(n => n.id === renderTarget)) setRenderTarget(doc.nodes.find(n => n.type === 'output')?.id ?? '') }, [doc, renderTarget])
  useEffect(() => { setStart(0); setEnd(Math.max(0, (source?.frameCount ?? state.generatedFrames) - 1)) }, [source?.id, source?.frameCount])
  useEffect(() => { if (!source && Number.isInteger(end) && end >= 0 && end < 100000) useEditor.setState({ generatedFrames: end + 1 }) }, [source, end])
  // Keep the transferred preview canvas mounted when viewing a rendered movie.
  useEffect(() => { setInspector('frame') }, [selected, port, state.activeTab])
  useEffect(() => { if (inspector !== 'movie') moviePlayer.current?.pause() }, [inspector])
  useEffect(() => { if (state.movie) { setInspector('movie'); setPane('preview') } }, [state.movie?.url])
  const seek = (time: number) => useEditor.setState({ frame: Math.max(0, Math.min(frameCount - 0.001, time)) })
  const loadSample = async (name: string) => {
    setSample(name)
    if (!name) return
    try {
      const response = await fetch(`${import.meta.env.BASE_URL}samples/${encodeURIComponent(name)}.mp4`)
      if (!response.ok || !response.headers.get('content-type')?.includes('video')) throw new Error('Example clips are local and are not included in Git. Run npm run samples, or open your own MP4.')
      loadVideo(new File([await response.blob()], `${name}.mp4`, { type: 'video/mp4' }))
    } catch (error) { useEditor.setState({ error: String(error) }) }
  }
  const renderCount = end >= start ? outputCount(start, end, timelineFps, fps) : 0
  return <div className="app-shell"><Global styles={styles} />
    <header className="app-header"><div className="brand"><span className="brand-mark">cv</span><strong>opencv-wasm</strong><span className="brand-divider" /><span className="eyebrow">VISUAL EDITOR</span></div><div className="header-actions"><a className="docs-link" href={import.meta.env.MODE === 'site' ? '/' : (import.meta.env.VITE_DOCS_URL || 'https://opencv.banou.dev/')}>Docs ↗</a><ThemeSelect /><span className={`engine-state ${ready && !state.fatal ? 'online' : ''}`}><i />{state.fatal ? 'Engine unavailable' : ready ? 'Engine ready' : 'Starting engine'}</span><button disabled={locked || !supportsProjectFolder()} title={supportsProjectFolder() ? 'Open a folder to autosave the graph, retain media, and save exports' : 'Folder access requires desktop Chrome on localhost or HTTPS'} onClick={() => void openProjectFolder()}>Project folder…</button><button disabled={locked} onClick={() => projectInput.current?.click()}>Open graph</button><button disabled={locked} onClick={() => prefabInput.current?.click()}>Insert prefab</button><button onClick={() => { void saveGraph().catch(() => {}) }}>Save graph</button></div></header>
    <input hidden ref={videoInput} type="file" accept="video/mp4,.mp4,.m4v,.mov" onChange={e => { const file = e.target.files?.[0]; if (file) { setSample(''); loadVideo(file) } e.target.value = '' }} />
    <input hidden ref={projectInput} type="file" accept=".json" onChange={async e => { const file = e.target.files?.[0]; e.target.value = ''; if (file) { try { state.replace(JSON.parse(await file.text())) } catch (error) { useEditor.setState({ error: String(error) }) } } }} />
    <input hidden ref={prefabInput} type="file" accept=".json" onChange={async e => { const file = e.target.files?.[0]; e.target.value = ''; if (file) { try { state.insert(JSON.parse(await file.text())) } catch (error) { useEditor.setState({ error: String(error) }) } } }} />
    <section className="source-strip"><div className="clip-controls"><button className="primary" disabled={busy === 'bake'} onClick={() => videoInput.current?.click()}>＋ Open video</button>{examples.length > 0 && <select aria-label="Example clip" value={sample} disabled={busy === 'bake'} onChange={e => void loadSample(e.target.value)}><option value="">Local samples…</option>{examples.map(name => <option key={name} value={name}>{name.replaceAll('-', ' ')}</option>)}</select>}</div><div className="clip-info">{source ? <><strong>{source.name}</strong><span>{source.width} × {source.height}<b>·</b>{source.frameCount} frames<b>·</b>{source.fps.toFixed(3)} fps</span></> : <><strong>Your next computer vision experiment</strong><span>Drop an MP4, or open Procedural stripe texture to generate without a video.</span></>}</div><button className="quiet" onClick={() => setShowInfo(!showInfo)}>{showInfo ? 'Hide' : 'Media'} details ⓘ</button></section>
    <div className="workspace-notices">
    {projectFolder.name && <div className="project-folder-strip" data-testid="folder-state" data-pending={projectFolder.queued}><strong>▣ {projectFolder.name}</strong><span>{projectFolder.status}{projectFolder.dirty && projectFolder.status.startsWith('Saved exports/') ? ' · Graph unsaved' : ''}</span><small>Graph autosaves · media/ originals · exports/ images & videos</small><button onClick={() => { void syncProject().catch(() => {}) }}>Save now</button></div>}
    {projectFolder.error && <div className="error-banner" role="alert"><strong>Project folder</strong><span>{projectFolder.error}</span></div>}
    {Object.keys(state.assets).length > 1 && <div className="project-folder-strip"><label>Timeline reference <select aria-label="Timeline reference" disabled={locked} value={source?.id ?? ''} onChange={e => useEditor.setState({ source: state.assets[e.target.value], frame: 0, result: null })}>{Object.values(state.assets).map(asset => <option key={asset.id} value={asset.id}>{asset.name} · {asset.fps.toFixed(3)} fps</option>)}</select></label><small>Source nodes keep their own clips. Frame indices align; this clip sets the timeline rate.</small></div>}
    {showInfo && <div className="info-banner">{source ? <>{source.codec} · {source.decoder} decoder. {source.warnings.join(' ')}</> : <>Files are processed locally. MP4 is supported; remux MKV to MP4 first. This video path reads 8-bit images. Generated videos contain no audio.</>}</div>}
    {state.error && <div className="error-banner" role="alert"><strong>{state.fatal ? 'Engine error' : 'Could not complete this step'}</strong><span>{state.error}</span>{state.fatal && <button onClick={() => window.location.reload()}>Reload engine</button>}{!state.fatal && <button aria-label="Dismiss error" onClick={() => useEditor.setState({ error: '' })}>×</button>}</div>}
    </div>
    <nav className="workspace-switcher" aria-label="Workspace panels"><button aria-pressed={pane === 'graph'} onClick={() => setPane('graph')}>Node graph</button><button aria-pressed={pane === 'preview'} onClick={() => setPane('preview')}>Inspector</button></nav>
    <main className="workspace" data-pane={pane} ref={workspace} style={{ gridTemplateColumns: `${left}% 6px minmax(0, 1fr)` }}>
      <section className="graph-panel"><div className="panel-heading"><div><span className="eyebrow">01 / BUILD</span><h1>Follow the pixels.</h1></div><div className="prefab-controls"><label className="template-label">Prefabs · editable basic nodes<select aria-label="Prefab library" disabled={locked} value={preset} onChange={e => setPreset(e.target.value as typeof preset)}><option value="texture">Procedural stripe texture</option><option value="motionVectors">Regional motion vectors</option><option value="motion">Camera in-betweens</option><option value="difference">Compare neighboring frames</option><option value="filter">Prepare an image</option><option value="crop">Process a region</option><option value="pyramid">Explore Laplacian pyramids</option><option value="mask">Changed-pixel mask</option></select></label><div><button disabled={locked} onClick={() => state.replace(explicitGraph(preset))} title="Open this prefab as the working graph">Open</button><button disabled={locked} onClick={() => state.insert(explicitGraph(preset))} title="Insert an independent copy below your existing nodes">＋ Insert</button></div></div></div><EditorTabs /><div className="graph-flow-guide">Video → Extract Frame, or Generate → Frame operations + Time → Output → Render video</div><Graph /><div className="graph-bottom">{[...new Set(view.nodes.flatMap(n => { const spec = specFor(n, view); return [...spec.inputs, ...spec.outputs].map(p => p.type) }))].map(type => <span key={type} title={PORT_LABELS[type]}><i style={{ background: PORT_COLORS[type] }} />{PORT_LABELS[type]}</span>)}<button className="quiet" onClick={() => { const all = view.nodes.every(n => state.previews[n.id]); for (const n of view.nodes) if (!!state.previews[n.id] === all) state.togglePreview(n.id) }}>{view.nodes.every(n => state.previews[n.id]) ? 'Hide all previews' : 'Show all previews'}</button><span className="muted">{view.nodes.length} nodes</span></div></section>
      <div className="splitter" role="separator" aria-label="Resize graph and preview" aria-orientation="vertical" onPointerDown={e => e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e => { if (!e.currentTarget.hasPointerCapture(e.pointerId)) return; const rect = workspace.current?.getBoundingClientRect(); if (rect) setLeft(Math.min(72, Math.max(28, (e.clientX - rect.left) / rect.width * 100))) }} onPointerUp={e => e.currentTarget.releasePointerCapture(e.pointerId)} />
      <section className="inspect-panel" data-selected={selected} data-computed-node={result?.selected} data-computed-frame={result?.frame}><div className="panel-heading"><div><span className="eyebrow">02 / INSPECT</span><h2>{spec?.title ?? 'Select for preview'}</h2></div>{spec && <select aria-label="Output socket" value={port ?? outputs[0]?.id ?? ''} disabled={locked || outputs.length < 2} onChange={e => useEditor.setState({ port: e.target.value })}>{outputs.length ? outputs.map(p => <option key={p.id} value={p.id}>{p.label}</option>) : <option value="">Final image</option>}</select>}</div>
        <nav className="inspector-switcher" aria-label="Inspector view"><button aria-pressed={inspector === 'frame'} onClick={() => setInspector('frame')}>Node preview</button><button aria-pressed={inspector === 'movie'} onClick={() => setInspector('movie')}>Rendered video{state.movie && <span className="ready-dot" />}</button></nav>
        <div className="frame-panel" hidden={inspector !== 'frame'}>
        <div className="step-strip" aria-label="Inspect each step">{flow.map((n, i) => <button key={n.id} disabled={busy === 'bake'} className={selected === n.id ? 'active' : ''} onClick={() => state.select(n.id)}><span>{String(i + 1).padStart(2, '0')}</span>{specFor(n, view).title}</button>)}</div>
        <Preview />
        <div className="view-options"><label>View gain<select aria-label="View gain" disabled={locked} value={state.gain} onChange={e => useEditor.setState({ gain: Number(e.target.value) })}>{[1, 2, 4, 8, 16].map(v => <option key={v} value={v}>{v}×</option>)}</select></label><span>{result?.range === 'signed' ? 'Signed difference · middle gray = zero' : 'Gain affects this preview only'}</span><code>{result && (result.width ? `${result.width} × ${result.height}` : PORT_LABELS[result.kind])}</code></div>
        <details className="node-details"><summary>About this step <code>{spec?.algorithm}</code></summary><div className="node-explanation">{node && spec ? <><div className="explanation-title"><span className="eyebrow">WHAT THIS STEP DOES</span><code>{spec.algorithm}</code></div><p>{explanations[node.type]?.[0] ?? spec.description}</p><p className="muted">{explanations[node.type]?.[1] ?? (node.type === 'group' ? 'Double-click to open the internal graph. Its typed interface is editable, and changes apply to every instance.' : 'Connect a matching typed output to any parameter socket to compute its value. Disconnect it to use the editable fallback. Image operations consume a frame and return a frame; extracting or changing time is explicit upstream.')}</p><div className="input-demands"><span className="eyebrow">SOURCE FRAMES</span>{result?.sources.length ? result.sources.map(({ asset, frame }) => <code key={`${asset}:${frame}`} title="Actual decoded dependency, after resolving parameter wires">{state.assets[asset]?.name ?? asset} · #{frame}</code>) : <span className="muted">{result ? 'No source frames were decoded for this value.' : 'Evaluate this step to see its source frames.'}</span>}</div></> : <p>Right-click a node and choose Select for preview to see its image, data and explanation here.</p>}</div></details>
        </div>
      <div className="render-preview" hidden={inspector !== 'movie'}>{state.movie ? <><FramePlayer ref={moviePlayer} key={state.movie.url} movie={state.movie} /><div className="movie-caption"><span>{state.movie.label} · {state.movie.count} frames · {state.movie.fps} fps{state.movie.cancelled ? ' · partial render' : ''}<small>Press &lt; / &gt; to step frames. Snapshot from the last render; graph edits do not change this video.</small></span><button onClick={async () => { if (state.movie && await ensureProjectFolder()) saveBlob(await (await fetch(state.movie.url)).blob(), 'opencv-output.mp4') }}>Save MP4 to folder</button></div></> : <div className="render-empty"><span>▷</span><strong>Your generated video lives here.</strong><p>Build your own chain, or open an editable prefab.<br />Scrub between frames first to inspect the generated positions.</p></div>}</div>
      </section>
    </main>
    <section className="timeline"><div className="time-heading"><span className="eyebrow">{source ? 'SOURCE TIME' : 'GENERATED TIME'}</span><code data-testid="frame-time">{frame.toFixed(3)}</code><span className="muted">frames</span></div><button aria-label="Previous frame" disabled={!ready || locked || frame < 1} onClick={() => seek(Math.floor(frame) - 1)}>‹</button><input aria-label="Source frame" className="frame-number" type="number" disabled={!ready || locked} min={0} max={frameCount - 1} step={1} value={Math.floor(frame)} onChange={e => { if (Number.isInteger(e.target.valueAsNumber)) seek(e.target.valueAsNumber) }} /><button aria-label="Next frame" disabled={!ready || locked || frame >= frameCount - 1} onClick={() => seek(Math.floor(frame) + 1)}>›</button><div className="timeline-track"><TimelineSlider label="Timeline" max={frameCount - 1} step={1} value={Math.floor(frame)} disabled={!ready || locked} onChange={seek} /><div><span>0</span><span>{`${((frameCount - 1) / timelineFps).toFixed(2)} s · ${timelineFps.toFixed(2)} fps`}</span><span>{frameCount - 1}</span></div></div><label className="subframe">Between frames <code>+{(frame % 1).toFixed(2)}</code><TimelineSlider label="Subframe fraction" max={0.95} step={0.05} value={frame % 1} disabled={!ready || locked} onChange={value => seek(Math.floor(frame) + value)} /></label></section>
    <section className="render-section" aria-label="Render controls"><span className="eyebrow">RENDER</span><div className="render-settings"><div className="render-controls"><label>Target<select aria-label="Render target" disabled={locked} value={renderTarget} onChange={e => setRenderTarget(e.target.value)}>{doc.nodes.filter(n => n.type === 'output').map((n, i) => <option key={n.id} value={n.id}>Output {i + 1}</option>)}</select></label><label>From frame<input aria-label="Render first frame" disabled={locked} type="number" min={0} max={source ? frameCount - 1 : 99999} step={1} value={start} onChange={e => setStart(e.target.valueAsNumber)} /></label><label>Through frame<input aria-label="Render last frame" disabled={locked} type="number" min={start} max={source ? frameCount - 1 : 99999} step={1} value={end} onChange={e => setEnd(e.target.valueAsNumber)} /></label><label>Output fps<select aria-label="Render fps" disabled={locked} value={fps} onChange={e => setFps(Number(e.target.value))}>{[24, 25, 30, 50, 60, 120].map(n => <option key={n}>{n}</option>)}</select></label></div><p className="render-note">{Number.isFinite(renderCount) ? `${renderCount} output frames · ${(renderCount / fps).toFixed(2)} s · silent H.264 MP4` : 'Choose a valid frame range.'} {!source && 'Generated timeline: 24 fps; no video input required.'} {doc.nodes.some(n => n.type === 'motion' || n.type === 'delta' || n.type === 'phaseCorrelation') && 'Rendering repeats the last source frame when a next frame is unavailable.'}</p><div className="render-action"><button className="quiet" aria-pressed={inspector === 'movie'} onClick={() => { setInspector('movie'); setPane('preview') }}>View video</button>{busy === 'bake' ? <><button className="danger" onClick={cancel} disabled={state.cancelling}>{state.cancelling ? 'Finishing partial video…' : 'Stop and keep completed frames'}</button><code>{state.progress?.done ?? 0} / {state.progress?.total || '…'}</code></> : <button className="primary" disabled={!ready || !renderTarget || locked || state.fatal || !Number.isInteger(start) || !Number.isInteger(end) || end < start} onClick={() => bake(start, end, fps, renderTarget)}>▷ Render video</button>}</div>{busy === 'bake' && <progress value={state.progress?.done ?? 0} max={state.progress?.total || 1} />}</div>
</section>
    <footer data-testid="engine-status" data-state={busy} data-request={result?.request ?? 0}><span><i className={ready ? 'ready' : ''} />{busy === 'load' ? 'Indexing video…' : busy === 'bake' ? 'Rendering output…' : busy === 'inspect' ? 'Computing…' : result ? `Evaluated in ${Math.round(result.elapsed)} ms` : 'Ready for your experiment'}</span><span>{result ? `${Math.round(result.cacheBytes / 1024 ** 2)} MiB / 512 MiB result cache · ${result.cacheEntries} entries` : 'OpenCV WASM · WebGPU preview'}<b>·</b>Local processing</span></footer>
  </div>
}
