import { css } from '@emotion/react'

export const styles = css`
  :root { color-scheme: dark; font-family: 'DM Sans Variable', sans-serif; color: #e0e7df; background: #101310; font-synthesis: none; }
  * { box-sizing: border-box; } body { margin: 0; } button, input, select, a { -webkit-tap-highlight-color: transparent; } button, input, select { font: inherit; }
  button, select, .button { color: #d7dfd5; background: #252c25; border: 1px solid #394338; border-radius: 5px; padding: 7px 11px; font-size: 12px; cursor: pointer; transition: background .12s, border-color .12s; }
  button:hover:not(:disabled), .button:hover { background: #344032; border-color: #758b6e; } button:disabled, select:disabled, input:disabled { opacity: .42; cursor: default; }
  button.primary { background: #b5d49c; color: #172113; border-color: #b5d49c; font-weight: 700; } button.primary:hover:not(:disabled) { background: #c9e8b0; }
  button.active { border-color: #b5d49c; color: #c5e7ae; background: #293526; } button.quiet { background: transparent; border-color: transparent; }
  button.danger { color: #efbf92; border-color: #815e3e; } input[type=number] { min-width: 0; color: #e7ece4; background: #151a15; border: 1px solid #384136; border-radius: 4px; padding: 6px; font: 12px 'JetBrains Mono', monospace; }
  input[type=range] { accent-color: #b5d49c; height: 5px; cursor: pointer; } input[type=checkbox] { accent-color: #b5d49c; }
  button:focus-visible, input:focus-visible, select:focus-visible, a:focus-visible { outline: 2px solid #c5e7ae; outline-offset: 3px; }
  h1, h2, p { margin: 0; } h1, h2 { font-size: 21px; font-weight: 500; letter-spacing: -.6px; } code, .eyebrow { font-family: 'JetBrains Mono', monospace; }
  code { font-size: 11px; } .eyebrow { font-size: 9px; letter-spacing: 1.7px; color: #9caa94; font-weight: 500; white-space: nowrap; } .muted { color: #99a393; } .button { text-decoration: none; white-space: nowrap; }
  .app-header { height: 64px; padding: 0 25px; display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #30382d; }
  .brand { display: flex; align-items: center; gap: 13px; } .brand strong { font-size: 24px; letter-spacing: -1px; font-weight: 650; } .brand-mark { width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; border: 1px solid #8fa77b; color: #c5e7ae; font-size: 27px; border-radius: 8px; line-height: 1; padding-bottom: 6px; } .brand-mark span { color: #efbc7b; }
  .brand-divider { width: 1px; height: 20px; background: #3c4436; margin: 0 4px; } .header-actions { display: flex; align-items: center; gap: 8px; } .engine-state { font-size: 11px; color: #969f90; margin-right: 14px; display: flex; gap: 7px; align-items: center; } .engine-state i, footer i { width: 6px; height: 6px; border-radius: 50%; display: inline-block; background: #e4b886; } .engine-state.online i, footer i.ready { background: #b5d49c; }
  .source-strip { display: flex; align-items: center; gap: 22px; padding: 15px 25px; background: #191f18; border-bottom: 1px solid #30382d; } .clip-controls { display: flex; gap: 8px; } .clip-info { display: flex; flex: 1; flex-wrap: wrap; align-items: center; gap: 15px; font-size: 12px; } .clip-info span { color: #a0ad98; } b { font-weight: 400; margin: 0 9px; color: #62705b; }
  .info-banner, .error-banner { padding: 12px 25px; font-size: 12px; line-height: 1.65; border-bottom: 1px solid #505240; background: #2b3022; color: #cdd2b8; } .error-banner { display: flex; align-items: center; gap: 15px; color: #eccab2; background: #33291f; border-color: #68523b; overflow-wrap: anywhere; } .error-banner span { flex: 1; }
  .workspace { display: grid; min-height: 620px; height: calc(100vh - 254px); max-height: 1100px; border-bottom: 1px solid #394232; }
  .graph-panel { display: flex; flex-direction: column; min-width: 0; background: #151914; overflow: hidden; } .panel-heading { padding: 20px 22px 16px; min-height: 91px; display: flex; justify-content: space-between; align-items: center; gap: 12px; } .panel-heading h1, .panel-heading h2 { margin-top: 5px; } .template-label { display: flex; flex-direction: column; gap: 5px; font-size: 10px; color: #99a88d; }
  .graph-surface { position: relative; flex: 1; min-height: 280px; }
  .graph-help { position: absolute; bottom: 19px; right: 15px; max-width: calc(100% - 72px); font-size: 10px; color: #9caa94; background: #171d16e8; padding: 6px 9px; border-radius: 4px; pointer-events: none; } .graph-bottom { padding: 11px 20px; display: flex; gap: 16px; align-items: center; border-top: 1px solid #30382d; font-size: 10px; } .graph-bottom span { display: flex; align-items: center; gap: 6px; } .graph-bottom span:last-child { margin-left: auto; } .graph-bottom i { width: 5px; height: 5px; border-radius: 50%; }
  .react-flow { --xy-background-color: transparent; --xy-controls-button-background-color: #252c25; --xy-controls-button-background-color-hover: #344032; --xy-controls-button-color: #cfdfc7; --xy-controls-button-border-color: #45503c; }
  .react-flow__controls { box-shadow: none; border: 1px solid #3a4533; border-radius: 5px; overflow: hidden; margin: 15px; }
  .react-flow__node { border-radius: 9px; } .operation { width: 230px; border: 1px solid #485340; border-radius: 8px; background: #22291f; box-shadow: 0 7px 16px #0003; color: #dbe6d3; } .operation.chosen { border-color: #c5e7ae; box-shadow: 0 0 0 1px #b5d49c, 0 8px 20px #0005; }
  .operation-head { display: flex; align-items: center; gap: 9px; padding: 12px; border-bottom: 1px solid #3a4433; } .operation-head small { display: block; font: 8px 'JetBrains Mono', monospace; text-transform: uppercase; letter-spacing: 1.4px; color: #9fad92; margin-bottom: 4px; } .operation-head strong { font-size: 13px; font-weight: 600; } .op-symbol { font: 21px 'JetBrains Mono', monospace; color: #c5e7ae; width: 27px; text-align: center; } .op-symbol.motion { color: #9caef4; } .op-symbol.delta { color: #efbc7b; }
  .status-dot { width: 5px; height: 5px; border-radius: 50%; background: #56604e; margin-left: auto; } .status-dot.done { background: #c5e7ae; } .status-dot.running { background: #efbc7b; animation: blink .6s infinite alternate; } .status-dot.cached { background: #9caef4; } @keyframes blink { to { opacity: .3; } }
  .sockets { padding: 7px 0; } .socket { position: relative; height: 25px; display: flex; align-items: center; gap: 5px; padding: 0 13px; font-size: 10px; } .socket code { margin-left: auto; color: #b5c4a7; font-size: 9px; } .socket.output { justify-content: flex-end; color: #c4d4b9; } .react-flow__handle { width: 9px; height: 9px; border: 2px solid #1b2118; border-radius: 50%; } .react-flow__handle-left { left: 0; } .react-flow__handle-right { right: 0; }
  .menu-backdrop { position: fixed; inset: 0; z-index: 1000; cursor: default; }
  .node-menu { position: absolute; width: 480px; max-width: calc(100vw - 16px); background: #20261e; border: 1px solid #607153; border-radius: 8px; box-shadow: 0 18px 60px #0009; overflow: hidden; color: #dce8d2; }
  .menu-title { display: flex; gap: 12px; align-items: center; padding: 10px 14px; border-bottom: 1px solid #3b4633; font-size: 12px; font-weight: 600; } .menu-title code { margin-left: auto; color: #8ea17f; font-weight: 400; } .menu-title button { border: 0; padding: 0 3px; background: transparent; }
  .menu-search { display: flex; align-items: center; margin: 11px; border: 1px solid #718361; border-radius: 5px; padding: 0 10px; background: #121b0f; gap: 8px; } .menu-search span { font-size: 23px; color: #a9cb8f; } .menu-search input { background: transparent; color: #ddeed0; border: 0; outline: 0; padding: 10px 0; width: 100%; font-size: 12px; } .menu-search input:focus-visible { outline: 0; }
  .menu-context { display: flex; flex-wrap: wrap; gap: 5px; margin: 0 11px 10px; } .menu-context button { font-size: 10px; padding: 5px 8px; }
  .menu-body { display: grid; grid-template-columns: 125px 1fr; height: 307px; border-block: 1px solid #3b4633; } .menu-body.searching { grid-template-columns: 1fr; } .menu-body nav { padding: 6px; background: #181f15; border-right: 1px solid #3b4633; overflow: auto; } .menu-body nav button { display: flex; align-items: center; justify-content: space-between; width: 100%; border-color: transparent; padding: 6px 8px; border-radius: 3px; background: transparent; font-size: 11px; text-align: left; } .menu-body nav button.active { background: #35432c; color: #ccebb7; }
  .menu-results { overflow: auto; padding: 5px; } .menu-results > button { display: block; text-align: left; width: 100%; border-color: transparent; background: transparent; padding: 9px 10px; border-radius: 4px; } .menu-results button.highlighted { background: #35452c; border-color: #5f7850; } .menu-results strong { display: flex; justify-content: space-between; gap: 10px; font-size: 12px; font-weight: 550; } .menu-results small { color: #aac098; font-size: 8px; font-family: 'JetBrains Mono', monospace; font-weight: 400; } .menu-results button > span { display: block; color: #a1b494; font-size: 10px; line-height: 1.5; margin-top: 5px; } .menu-results > p { padding: 20px 12px; font-size: 12px; line-height: 1.7; color: #acb9a2; }
  .menu-hint { padding: 9px 12px; font-size: 9px; color: #a6b899; display: flex; justify-content: space-between; } .menu-hint span { color: #c2d9af; }
  .editor-tabbar { display: flex; gap: 2px; background: #12190f; border-block: 1px solid #3b4633; min-height: 34px; flex-shrink: 0; overflow-x: auto; } .editor-tab { display: flex; flex-shrink: 0; align-items: center; border-right: 1px solid #333f2c; border-bottom: 2px solid transparent; } .editor-tab.active { background: #273320; border-bottom-color: #b5d49c; } .editor-tab button { background: transparent; border: 0; border-radius: 0; font-size: 10px; padding: 9px 12px; white-space: nowrap; } .editor-tab button + button { padding-inline: 7px; color: #8ea57c; } .editor-tab code { font-size: 8px; color: #9cb38a; } .history-buttons { margin-left: auto; display: flex; align-items: center; gap: 3px; padding: 3px 7px; } .history-buttons button { padding: 2px 7px; font-size: 17px; background: transparent; border: 0; }
  .enter-group { margin: 0 10px 8px; width: calc(100% - 20px); font-size: 10px; background: #323c47; border-color: #5a6c81; color: #c2d1e6; padding: 6px; }
  .interface-editor { flex-shrink: 0; background: #20281b; border-bottom: 1px solid #46533a; max-height: 225px; overflow: auto; } .interface-editor summary { padding: 10px 15px; color: #c5deb3; cursor: pointer; font-size: 11px; } .interface-editor summary span { font-size: 9px; color: #94a984; margin-left: 12px; } .interface-content { display: flex; gap: 15px; padding: 4px 15px 14px; flex-wrap: wrap; } .definition-name { display: flex; flex-direction: column; gap: 6px; color: #9aac8d; font-size: 10px; width: 155px; } .interface-content input:not([type=number]) { background: #121a0e; border: 1px solid #43553a; border-radius: 4px; color: #ddebd3; padding: 5px 7px; font-size: 11px; min-width: 0; } .interface-ports { flex: 1; min-width: 225px; } .interface-port-heading { display: flex; justify-content: space-between; align-items: center; font-size: 10px; color: #a9bd99; margin-bottom: 7px; } .interface-port-heading button { font-size: 9px; padding: 3px 6px; } .interface-port { display: flex; gap: 4px; margin-top: 5px; } .interface-port input:not([type=number]) { flex: 1; width: 90px; } .interface-port select { font-size: 9px; padding: 3px 4px; max-width: 72px; } .interface-port input[type=number] { width: 51px; padding: 3px; font-size: 9px; } .interface-port > button { padding: 2px 5px; font-size: 10px; }
  .prefab-controls { display: flex; align-items: end; gap: 7px; } .prefab-controls > div { display: flex; gap: 4px; } .prefab-controls button { padding: 7px 9px; }
  .node-preview-toolbar { padding: 5px 9px; display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #3a4433; border-radius: 8px 8px 0 0; background: #192016; font: 7px 'JetBrains Mono', monospace; letter-spacing: 1px; color: #8fa77b; } .node-preview-toolbar button { font-size: 8px; padding: 2px 5px; border-color: transparent; background: transparent; letter-spacing: 0; color: #bbd6a7; }
  .node-thumbnail { height: 130px; background: #0a1007; position: relative; display: flex; align-items: center; justify-content: center; overflow: hidden; border-bottom: 1px solid #3a4433; }
  .node-thumbnail canvas { width: 100%; height: 100%; object-fit: contain; pointer-events: none; } .node-thumbnail > span { color: #8c9e7e; font-size: 10px; line-height: 1.6; text-align: center; padding: 14px; } .node-thumbnail strong { font: 25px 'JetBrains Mono', monospace; color: #efbc7b; } .node-thumbnail .thumbnail-error { color: #dfb690; } .thumbnail-frame { position: absolute; bottom: 5px; left: 5px; color: #d6e9c8; background: #0e180bcc; padding: 3px 5px; font-size: 8px; }
  .graph-bottom button { font-size: 10px; padding: 3px 6px; }
  .parameters { border-top: 1px solid #3a4433; padding: 9px 12px; display: flex; flex-direction: column; gap: 7px; } .parameters label { display: flex; align-items: center; justify-content: space-between; gap: 5px; font-size: 10px; color: #b3c0a8; } .parameters input[type=number] { width: 63px; font-size: 10px; padding: 4px; } .parameters select { font-size: 10px; padding: 4px; max-width: 90px; } .op-foot { padding: 8px 10px; border-top: 1px solid #3a4433; display: flex; justify-content: space-between; align-items: center; background: #1b2218; border-radius: 0 0 8px 8px; gap: 4px; } .op-foot code { font-size: 8px; color: #91a282; overflow: hidden; text-overflow: ellipsis; } .op-foot span { font: 8px 'JetBrains Mono', monospace; color: #bbcfae; white-space: nowrap; }
  .splitter { cursor: col-resize; background: #20271d; border-left: 1px solid #394232; border-right: 1px solid #394232; touch-action: none; } .splitter:hover { background: #718362; }
  .inspect-panel { background: #1b2119; min-width: 0; display: flex; flex-direction: column; overflow: auto; } .inspect-panel .panel-heading { flex-shrink: 0; } .step-strip { display: flex; padding: 0 18px 12px; gap: 5px; overflow: auto; flex-shrink: 0; } .step-strip button { white-space: nowrap; font-size: 10px; padding: 7px 9px; } .step-strip button span { color: #8a9e7b; margin-right: 6px; font-family: 'JetBrains Mono', monospace; }
  .preview-tools { display: flex; align-items: center; justify-content: space-between; gap: 10px; padding: 8px 16px; border-block: 1px solid #303b2a; font-size: 10px; } .preview-tools > div { display: flex; align-items: center; gap: 8px; } .preview-tools button { padding: 4px 7px; font-size: 10px; background: #1d2619; }
  .image-viewport { position: relative; overflow: hidden; min-height: 220px; flex: 1 0 270px; background-color: #0e120d; background-image: linear-gradient(45deg, #ffffff03 25%, transparent 25%), linear-gradient(-45deg, #ffffff03 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #ffffff03 75%), linear-gradient(-45deg, transparent 75%, #ffffff03 75%); background-size: 20px 20px; background-position: 0 0, 0 10px, 10px -10px, -10px 0; cursor: crosshair; touch-action: none; }
  .image-viewport canvas { position: absolute; transform: translate(-50%, -50%); pointer-events: none; } .image-viewport:active { cursor: grabbing; }
  .empty-preview, .scalar-preview { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; flex-direction: column; text-align: center; gap: 16px; pointer-events: none; } .empty-preview p { color: #99a98e; font-size: 12px; line-height: 1.8; } .empty-icon { font-size: 33px; color: #99b187; border: 1px solid #3a4831; border-radius: 50%; width: 65px; height: 65px; display: grid; place-items: center; } .scalar-preview strong { font: 48px 'JetBrains Mono', monospace; color: #efbc7b; } .scalar-preview > span:last-child { font-size: 11px; color: #a8b69d; }
  .preview-badge { position: absolute; top: 12px; right: 12px; border: 1px solid #667454; background: #192313e8; border-radius: 4px; padding: 7px 10px; font-size: 11px; color: #c5e7ae; }
  .motion-key { position: absolute; bottom: 12px; left: 12px; padding: 9px 12px; border-radius: 5px; background: #152010ee; border: 1px solid #536846; display: flex; flex-direction: column; gap: 5px; font-size: 10px; pointer-events: none; } .motion-key strong { font: 11px 'JetBrains Mono', monospace; color: #c5e7ae; }
  .pixel-bar { display: flex; align-items: center; gap: 9px; min-height: 36px; padding: 5px 16px; background: #141b11; border-block: 1px solid #303b2a; font-size: 10px; } .pixel-bar button { margin-left: auto; padding: 3px 7px; font-size: 10px; } .pixel-bar code { font-size: 10px; } .swatch { width: 12px; height: 12px; border: 1px solid #909f87; border-radius: 2px; }
  .view-options { padding: 10px 16px; display: flex; gap: 12px; align-items: center; font-size: 10px; color: #9bab90; } .view-options label { display: flex; gap: 8px; align-items: center; white-space: nowrap; } .view-options select { font-size: 10px; padding: 3px 6px; } .view-options > code { margin-left: auto; }
  .node-explanation { padding: 15px 20px 17px; border-top: 1px solid #303b2a; background: #20271c; } .explanation-title { display: flex; justify-content: space-between; gap: 12px; align-items: center; margin-bottom: 10px; } .explanation-title code { color: #bfd7a9; font-size: 10px; } .node-explanation p { font-size: 11px; line-height: 1.75; } .node-explanation p + p { margin-top: 7px; } .input-demands { display: flex; gap: 7px; align-items: center; margin-top: 12px; flex-wrap: wrap; } .input-demands .eyebrow { margin-right: 6px; } .input-demands button { font: 10px 'JetBrains Mono', monospace; padding: 3px 7px; } .input-demands .muted { font-size: 10px; }
  .timeline { min-height: 83px; padding: 15px 24px; display: flex; gap: 10px; align-items: center; background: #191f17; border-bottom: 1px solid #394232; } .time-heading { display: flex; align-items: center; gap: 8px; margin-right: 12px; } .time-heading code { font-size: 19px; color: #c5e7ae; } .time-heading .muted { font-size: 10px; } .timeline button { padding: 6px 10px; } .frame-number { width: 62px; } .timeline-track { display: flex; flex: 1; flex-direction: column; gap: 10px; margin: 0 22px 0 12px; } .timeline-track input { width: 100%; margin: 8px 0 0; } .timeline-track > div { display: flex; justify-content: space-between; font: 9px 'JetBrains Mono', monospace; color: #92a086; } .subframe { width: 175px; font-size: 10px; color: #a7b69a; display: flex; flex-wrap: wrap; gap: 9px; } .subframe code { margin-left: auto; color: #c5e7ae; } .subframe input { width: 100%; }
  .render-section { display: grid; grid-template-columns: 1fr 1fr; padding: 30px; gap: 40px; border-bottom: 1px solid #394232; background: #151b12; } .render-settings h2 { margin: 7px 0 10px; font-size: 25px; } .render-settings p { color: #9ead93; font-size: 12px; line-height: 1.8; } .render-controls { display: flex; flex-wrap: wrap; gap: 12px; margin: 22px 0 10px; } .render-controls label { display: flex; flex-direction: column; gap: 7px; font-size: 10px; color: #b6c3ac; } .render-controls input, .render-controls select { width: 110px; } .render-settings p.render-note { max-width: 460px; font-size: 10px; } .render-action { display: flex; gap: 20px; align-items: center; margin-top: 17px; } progress { width: 100%; height: 4px; margin-top: 15px; accent-color: #b5d49c; }
  .render-preview { min-height: 260px; border: 1px solid #384731; border-radius: 7px; background: #10160d; overflow: hidden; display: flex; flex-direction: column; } .render-preview video { width: 100%; max-height: 390px; min-height: 200px; object-fit: contain; background: #080c06; } .render-empty { display: flex; flex: 1; justify-content: center; align-items: center; flex-direction: column; gap: 12px; color: #8fa77b; text-align: center; padding: 25px; } .render-empty > span { font-size: 34px; } .render-empty strong { font-size: 13px; font-weight: 500; color: #b0c2a2; } .render-empty p { font-size: 11px; line-height: 1.8; }
  .movie-caption { display: flex; padding: 11px 15px; align-items: center; justify-content: space-between; gap: 15px; font-size: 11px; color: #bed2ae; } .movie-caption small { display: block; margin-top: 5px; color: #91a084; font-size: 9px; }
  footer { display: flex; gap: 20px; justify-content: space-between; align-items: center; min-height: 37px; padding: 8px 25px; font-size: 9px; color: #96a68a; } footer > span { display: flex; align-items: center; gap: 8px; }
  @media (min-width: 1900px) { .workspace { min-height: 750px; } .image-viewport { flex-basis: 400px; } .node-explanation p { font-size: 13px; } }
  @media (max-width: 1100px) { .brand .eyebrow { display: none; } .clip-info { gap: 5px; } .time-heading .eyebrow, .preview-tools .muted { display: none; } .panel-heading { padding: 17px 13px; } .panel-heading h1, .panel-heading h2 { font-size: 18px; } .view-options > span { display: none; } .source-strip { gap: 12px; padding-inline: 15px; } }
  @media (max-width: 760px) { .app-header { padding: 0 12px; } .engine-state { display: none; } .source-strip { flex-wrap: wrap; } .clip-info { order: 3; flex-basis: 100%; } .workspace { display: flex; flex-direction: column; height: auto; max-height: none; } .splitter { display: none; } .graph-panel { min-height: 460px; } .inspect-panel { min-height: 620px; } .timeline { flex-wrap: wrap; padding: 14px; } .timeline-track { min-width: 200px; } .subframe { width: 140px; } .render-section { grid-template-columns: 1fr; padding: 20px; gap: 25px; } footer { flex-wrap: wrap; } .render-controls input, .render-controls select { width: 90px; } .brand-divider { display: none; } .header-actions { gap: 5px; } }

  .source-file { margin: 0 12px 12px; padding: 12px; border: 1px dashed #64745e; border-radius: 7px; display: grid; gap: 7px; background: #20291f; }
  .source-file.drag-over { background: #384e31; border-color: #c1e49b; }
  .source-file strong { font-size: 12px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .source-file span, .source-file small { font-size: 10px; color: #a6b89f; }
  .source-file button, .source-file select { font-size: 11px; width: 100%; min-width: 0; }
  .project-folder-strip { padding: 7px 24px; display: flex; align-items: center; gap: 16px; background: #1b241c; font-size: 12px; border-bottom: 1px solid #334032; }
  .project-folder-strip small { color: #9ca798; flex: 1; }
`
