import { test, expect } from '@playwright/test'

test('atlas filters, keyboard stages and exact API links work', async ({ page }) => {
  await page.goto('/algorithms/')
  await page.getByRole('searchbox', { name: 'Find an algorithm or a use case' }).fill('homography')
  await page.locator('.atlas-grid').getByRole('link', { name: /Homography and RANSAC/ }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Homography and RANSAC')
  const diagram = page.locator('algorithm-diagram').first()
  await diagram.getByRole('button', { name: '1 · Input' }).focus()
  await page.keyboard.press('Enter')
  await expect(diagram).toHaveAttribute('data-stage', '0')
  await expect(diagram.locator('.diagram-caption')).toContainText('Propose a homography')
  await page.locator('.reference-list a').filter({ hasText: /^findHomographyReference/ }).count().then(async count => {
    if (count) await page.locator('.reference-list a').filter({ hasText: /^findHomographyReference/ }).click()
    else await page.locator('a[href="/api/findHomography/"]').last().click()
  })
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('findHomography')
  await expect(page.locator('.parameters')).toContainText('srcPoints')
  await expect(page.locator('a[href*="github.com/opencv/opencv/blob/5.0.0/"]').first()).toBeVisible()
})

test('category and individual selections combine with search and reset together', async ({ page }) => {
  await page.goto('/algorithms/')
  const atlas = page.locator('.atlas-grid'), filters = page.locator('filter-list')
  const search = page.getByRole('searchbox', { name: 'Find an algorithm or a use case' })
  const gaussian = atlas.locator('a[href="/algorithms/gaussian-blur/"]'), canny = atlas.locator('a[href="/algorithms/canny/"]'), sobel = atlas.locator('a[href="/algorithms/sobel/"]')
  await expect(filters.locator('.filter-reset')).toBeDisabled()
  await page.getByRole('button', { name: 'No categories', exact: true }).click()
  await expect(filters.locator('.filter-empty')).toBeVisible()
  await page.getByRole('checkbox', { name: 'Filtering', exact: true }).check()
  await expect(gaussian).toBeVisible(); await expect(canny).toBeHidden()
  await page.getByRole('checkbox', { name: 'Edges', exact: true }).check()
  await expect(canny).toBeVisible()
  await search.fill('sobel')
  await expect(sobel).toBeVisible(); await expect(gaussian).toBeHidden()
  await page.locator('.individual-filters summary').click()
  await page.getByRole('searchbox', { name: 'Find in this selection' }).fill('sobel')
  await page.getByRole('checkbox', { name: 'Sobel derivatives', exact: true }).uncheck()
  await expect(sobel).toBeHidden(); await expect(filters.locator('.filter-empty')).toBeVisible()
  await page.getByRole('checkbox', { name: 'Sobel derivatives', exact: true }).check()
  await expect(sobel).toBeVisible()
  await page.getByRole('button', { name: 'Hide all algorithms', exact: true }).click()
  await expect(filters.locator('.filter-empty')).toBeVisible()
  await page.getByRole('button', { name: 'Show all algorithms', exact: true }).click()
  await expect(sobel).toBeVisible(); await expect(gaussian).toBeHidden()
  await page.getByRole('button', { name: 'Reset filters', exact: true }).click()
  await expect(search).toHaveValue('')
  await expect(page.getByRole('searchbox', { name: 'Find in this selection' })).toHaveValue('')
  await expect(gaussian).toBeVisible(); await expect(canny).toBeVisible()
  await expect(filters.locator('[data-search][hidden]')).toHaveCount(0)
  await expect(filters.locator('.filter-reset')).toBeDisabled()
})

test('sidebar categories and atlas filters are usable on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: /Menu/ }).click()
  const sidebar = page.locator('#starlight__sidebar')
  await sidebar.locator('summary').filter({ hasText: /^Algorithms$/ }).click()
  await sidebar.locator('summary').filter({ hasText: /^Filtering$/ }).click()
  await sidebar.getByRole('link', { name: 'Gaussian blur', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Gaussian blur')
  const expanded = await sidebar.locator('a[aria-current="page"]').evaluate(link => {
    const groups: string[] = []
    for (let parent = link.parentElement; parent; parent = parent.parentElement) if (parent instanceof HTMLDetailsElement && parent.open) groups.push(parent.querySelector('summary')!.textContent!.trim())
    return groups
  })
  expect(expanded).toEqual(['Filtering', 'Algorithms'])
  await page.goto('/algorithms/')
  await page.getByRole('button', { name: 'No categories', exact: true }).click()
  const edges = page.getByRole('checkbox', { name: 'Edges', exact: true })
  await edges.focus(); await page.keyboard.press('Space')
  await expect(page.locator('.atlas-grid a[href="/algorithms/canny/"]')).toBeVisible()
  await page.locator('.individual-filters summary').click()
  await page.getByRole('searchbox', { name: 'Find in this selection' }).fill('canny')
  await page.getByRole('checkbox', { name: 'Canny edges', exact: true }).uncheck()
  await expect(page.locator('.atlas-grid a[href="/algorithms/canny/"]')).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('reference search includes classes without public constructors and their inherited types', async ({ page }) => {
  await page.goto('/api/')
  await page.getByRole('searchbox', { name: 'Find a function, class, or type' }).fill('CLAHE')
  await page.locator('.reference-list a[href="/api/CLAHE/"]').click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('CLAHE')
  await expect(page.getByRole('heading', { name: 'apply', exact: true })).toBeVisible()
  await expect(page.locator('.callout').first()).toContainText('Native object')
})

test('global full-text search finds a generated API page', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Search/ }).first().click()
  const search = page.locator('dialog .pagefind-ui__search-input')
  await search.fill('GaussianBlur')
  await expect(page.locator('dialog .pagefind-ui__result-link').first()).toBeVisible()
  await expect(page.locator('dialog')).toContainText('GaussianBlur')
  await page.keyboard.press('Escape')
})

test('mobile layout, theme and navigation remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/algorithms/homography/')
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: /Menu/ }).click()
  await page.locator('#starlight__sidebar starlight-theme-select select').selectOption('light')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.locator('#starlight__sidebar a[href="/lab/"]').click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Image laboratory')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('desktop and mobile visual review artifacts', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1050 })
  await page.goto('/')
  await page.evaluate(() => { localStorage.setItem('starlight-theme', 'dark'); document.documentElement.dataset.theme = 'dark' })
  await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true })
  await page.goto('/algorithms/homography/')
  await page.screenshot({ path: 'test-results/homography-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/homography-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1050 })
  await page.goto('/lab/')
  await page.getByRole('button', { name: 'Load OpenCV and run' }).click()
  await expect(page.locator('image-lab')).toHaveAttribute('data-result', '1', { timeout: 45_000 })
  await page.screenshot({ path: 'test-results/lab-desktop.png', fullPage: true })
})

test('desktop page outline floats without reserving content or preview width', async ({ page }) => {
  for (const [width, theme] of [[1440, 'dark'], [1920, 'light']] as const) {
    await page.setViewportSize({ width, height: 1100 })
    await page.goto('/cookbook/motion-vectors/')
    await page.evaluate(theme => { document.documentElement.dataset.theme = theme }, theme)
    const toc = page.locator('.floating-toc')
    await expect(toc).toBeVisible()
    const initial = (await toc.boundingBox())!
    expect(initial.x + initial.width).toBeGreaterThan(width - 24)
    expect(initial.y).toBeGreaterThan(50)
    expect(await toc.evaluate(element => getComputedStyle(element).backgroundColor)).not.toBe('rgba(0, 0, 0, 0)')
    const lab = (await page.locator('image-lab').boundingBox())!
    expect(lab.x + lab.width).toBeGreaterThan(width - 60)
    expect(lab.x).toBeGreaterThan(260)
    await page.locator('.load-runtime').click()
    await expect(page.locator('image-lab')).toHaveAttribute('data-state', 'ready')
    const preview = (await page.locator('canvas.input').boundingBox())!
    expect(preview.width).toBeGreaterThan(width === 1440 ? 500 : 700)
    await expect(page.locator('canvas.input')).toHaveAttribute('width', '448')
    await toc.getByRole('link', { name: 'Try it with your images', exact: true }).click()
    await expect(page).toHaveURL(/#try$/)
    const scrolled = (await toc.boundingBox())!
    expect(Math.abs(scrolled.x - initial.x)).toBeLessThan(1)
    expect(Math.abs(scrolled.y - initial.y)).toBeLessThan(1)
    await page.screenshot({ path: `test-results/floating-outline-${theme}.png` })
    await toc.locator('summary').focus()
    await page.keyboard.press('Space')
    await expect(toc.locator('nav')).toBeHidden()
    expect((await toc.boundingBox())!.height).toBeLessThan(70)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
})
