/** Documentation for the hand-bound and adapted API that has no matching header comment. */
export const apiDocs = {
  WasmModule: 'Memory allocation exports for one isolated OpenCV WebAssembly instance.',
  EmbindModule: 'Native OpenCV functions, classes and constants compiled into this instance. Algorithms operate on handles belonging to the same instance.',
  EmbindString: 'Text accepted by native string parameters. JavaScript strings are encoded as UTF-8; byte buffers supply the encoded bytes directly.',
  'Mat.rows': 'Number of matrix rows. For tensors with more than two dimensions, use matSize instead.',
  'Mat.dims': 'Number of matrix or tensor dimensions. OpenCV 5 preserves one-dimensional tensors and zero-dimensional scalars. Use matSize for the extents.',
  'Mat.cols': 'Number of matrix columns. For tensors with more than two dimensions, use matSize instead.',
  'Mat.size': 'Return the two-dimensional image extent as width and height.',
  'Mat.data32U': 'Borrow an unsigned 32-bit pixel view of WASM memory. Use with CV_32U matrices; copy it before disposing the matrix or growing the heap.',
  'Mat.data64S': 'Borrow an exact signed 64-bit pixel view of WASM memory. Values are bigint. Use with CV_64S matrices; copy it before disposing the matrix or growing the heap.',
  'Mat.data64U': 'Borrow an exact unsigned 64-bit pixel view of WASM memory. Values are bigint. Use with CV_64U matrices; copy it before disposing the matrix or growing the heap.',
  MatShape: 'An owned OpenCV 5 tensor shape with up to ten dimensions and layout metadata. Construct from an IntVector, or use scalar() for a zero-dimensional tensor. Dispose the shape after use.',
  'MatShape.dims': 'Number of tensor dimensions. Zero denotes a scalar; a negative value denotes an empty shape.',
  'MatShape.layout': 'Numeric DATA_LAYOUT constant describing the dimension order.',
  'MatShape.C': 'Actual channel count when the shape uses a padded block layout.',
  'MatShape.size': 'Return the number of dimension extents. Use empty() to distinguish an empty shape from a scalar.',
  'MatShape.total': 'Return the product of dimension extents including block padding. Scalars contain one element; empty shapes contain zero.',
  'MatShape.vec': 'Copy the dimension extents into an owned IntVector. Dispose the returned vector.',
  'MatShape.str': 'Format the native shape and layout as a diagnostic string.',
  'MatShape.empty': 'Return whether this shape has zero elements.',
  'MatShape.isScalar': 'Return whether the shape has zero dimensions and represents a scalar.',
  'MatShape.clear': 'Reset this shape to the empty state.',
  'MatShape.channels': 'Return the channel extent according to the stored data layout.',
  'MatShape.hasSymbols': 'Return whether any negative extent represents a symbolic dimension.',
  'MatShape.expand': 'Compute the broadcast result of this shape and another shape. Return an owned shape, or throw when dimensions are incompatible.',
  'MatShape.erase': 'Remove the dimension at the supplied zero-based index. Throws when the index is outside the current dimensions.',
  'MatShape.toLayout': 'Convert dimension ordering to the requested numeric DATA_LAYOUT constant. The optional second argument supplies the block channel size. Return an owned shape.',
  'MatShape.scalar': 'Create an owned zero-dimensional shape containing one element.',
  'Filter2DParams.borderValue': 'Constant border scalar. OpenCV 5.0 currently requires all four components to be zero; filter2Dp throws for a nonzero borderValue.',
  'UMat.rows': 'Number of rows in this CPU-backed unified matrix.',
  'UMat.cols': 'Number of columns in this CPU-backed unified matrix.',
  'UMat.offset': 'Byte offset of this matrix view within its backing allocation.',
  'UMat.getMat': 'Map the CPU-backed unified matrix to an owned Mat header using the requested ACCESS_READ, ACCESS_WRITE or ACCESS_RW mode. Pixel storage is shared.',
  'UMat.get': 'Return an owned Mat header for CPU read access to this unified matrix. Pixel storage is shared; dispose the returned header.',
  'toUMat': 'Copy a matrix into an owned CPU-backed UMat. This build does not use an OpenCL device.',
  'flann_Index': 'A nearest-neighbor search index over feature vectors. Choose index and search parameters for the descriptor type and distance metric.',
  'flann_Index.build': 'Build or replace the search index from rows of feature descriptors and the chosen index parameters.',
  'flann_Index.knnSearch': 'Find up to knn nearest indexed feature vectors for each query row. Write their row indices and distances into the supplied output matrices.',
  'flann_Index.radiusSearch': 'Find indexed feature vectors within the distance radius of the query. Write up to maxResults indices and distances and return the native match count.',
  'flann_Index.save': 'Save the index structure to a path in this instance\'s virtual filesystem. Keep the original feature data for loading it again.',
  'flann_Index.load': 'Load a saved index using its original feature matrix. Return whether loading succeeded.',
  'flann_Index.release': 'Release the built search index while keeping this handle available for rebuilding.',
  'flann_Index.getDistance': 'Return the FLANN distance metric selected when the index was built.',
  'flann_Index.getAlgorithm': 'Return the FLANN index algorithm selected by the index parameters.',
  'flann_IndexParams': 'Named configuration values used when constructing a FLANN nearest-neighbor index.',
  'flann_SearchParams': 'Search configuration controlling the number of examined leaves, approximation tolerance and result ordering.',
  'flann_KDTreeIndexParams': 'Configuration for a randomized forest of kd-trees used to search floating-point descriptors.',
  'flann_LinearIndexParams': 'Configuration for exhaustive nearest-neighbor search over all descriptor rows.',
  'flann_LshIndexParams': 'Configuration for a locality-sensitive hashing index over binary descriptors.',
  'dnn_LayerParams': 'A DNN layer\'s instance name, type, learned blobs and named configuration values.',
  'dnn_LayerParams.name': 'Instance name identifying this layer within the network.',
  'dnn_LayerParams.type': 'Registered layer implementation name, such as ReLU or a custom TypeScript layer type.',
  'dnn_LayerParams.blobs': 'Learned parameter tensors associated with this layer.',
  'AsyncArray.release': 'Release this asynchronous result reference and its associated storage.',
  'AsyncArray.wait_for': 'Wait up to the supplied timeout for the result and return whether it became ready. Native asynchronous execution backends are not enabled in this build.',
  'AsyncArray.valid': 'Return whether this object holds an asynchronous result state.',
  'FileNode.at': 'Read a sequence element by zero-based index and return its file-node view.',
  'CLAHE.collectGarbage': 'Release cached working buffers used by contrast-limited adaptive histogram equalization.',
  'Subdiv2D.symEdge': 'Return the directed edge opposite to the supplied subdivision edge.',
  'ml_TrainData.shuffleTrainTest': 'Randomly repartition the current training and test sample indices while preserving the split sizes.',
  'ml_StatModel.empty': 'Return whether the statistical model has no learned parameters.',
  'ml_TrainData.getLayout': 'Return ROW_SAMPLE or COL_SAMPLE to indicate how samples are arranged in the data matrix.',
  'ml_TrainData.getNTrainSamples': 'Return the number of samples in the training partition.',
  'ml_TrainData.getNTestSamples': 'Return the number of samples in the test partition.',
  'ml_TrainData.getNSamples': 'Return the total number of selected samples.',
  'ml_TrainData.getNVars': 'Return the number of selected input variables per sample.',
  'ml_TrainData.getNAllVars': 'Return the number of input variables before variable selection.',
  'ml_TrainData.getSamples': 'Return an owned matrix header for the input sample data in its original layout.',
  'ml_TrainData.getMissing': 'Return the matrix marking missing values in the input samples.',
  'Feature2D.descriptorSize': 'Return the number of elements in one descriptor produced by this feature algorithm.',
  'Feature2D.descriptorType': 'Return the OpenCV element type of the descriptor matrix produced by this algorithm.',
  'Feature2D.defaultNorm': 'Return the distance norm recommended for matching this algorithm\'s descriptors.',
  'BOWTrainer.clear': 'Discard the descriptor sets accumulated for visual-vocabulary training.',
  'plot_Plot2d.render': 'Render the configured two-dimensional plot into the supplied output image.',
  'ppf_match_3d_Pose3D.printPose': 'Print this pose\'s transformation and vote information through the runtime\'s output callback.',
  'dnn_DictValue.isInt': 'Return whether this parameter stores integer values.',
  'dnn_DictValue.isReal': 'Return whether this parameter stores floating-point values.',
  'dnn_DictValue.isString': 'Return whether this parameter stores text values.',
  'CascadeClassifier.isOldFormatCascade': 'Return whether the loaded classifier uses the legacy Haar cascade format.',
  'HistogramCostExtractor.buildCostMatrix': 'Compute pairwise histogram matching costs from the two descriptor sets and fill the supplied cost matrix.',
  'detail_CameraParams.K': 'Construct and return the 3 by 3 camera intrinsic matrix from focal length, aspect ratio and principal point.',
  'detail_FeaturesMatcher.isThreadSafe': 'Return whether the native matcher reports that its implementation supports concurrent use.',
  'detail_BestOf2NearestMatcher.collectGarbage': 'Release temporary buffers retained by this feature matcher.',
  'ximgproc_AdaptiveManifoldFilter.collectGarbage': 'Release temporary buffers retained by the adaptive manifold filter.',
  'CV_MAT_DEPTH': 'Extract the scalar element depth from a combined OpenCV matrix type code.',
  'rotatedRectPoints': 'Return the four corners of a rotated rectangle as independent point values.',
  'rotatedRectBoundingRect': 'Return the smallest upright integer rectangle containing the rotated rectangle.',
  'rotatedRectBoundingRect2f': 'Return the upright floating-point bounds of the rotated rectangle.',
  'empty_array_desc': 'Create an empty array descriptor for native graph metadata. Array element type is determined by the graph node.',
  'empty_gopaque_desc': 'Create an empty opaque-value descriptor for native graph metadata.',
  'empty_scalar_desc': 'Create an empty scalar descriptor for native graph metadata.',
  'gapi_streaming_timestamp': 'Create an opaque signed 64-bit graph node reading the source timestamp in microseconds. Use it on an input node and supply metadata with applyWithMetadata or GraphStream.',
  'gapi_streaming_seq_id': 'Create an opaque signed 64-bit graph node reading the source sequence identifier. Use it on an input node; GraphStream numbers frames from zero unless metadata overrides it.',
  'gapi_streaming_seqNo': 'Create an opaque signed 64-bit sequence-number node. This is an alias for the native sequence metadata operation.',
  'GraphNode': 'A placeholder describing an input, intermediate value or output of a native graph. Supply runtime values to GComputation.apply instead of passing these nodes as pixel data.',
  'GraphPortType': 'Supported port names for custom native graph operations: matrices, four-component scalars, typed arrays and typed opaque values.',
  'GDrawPrim': 'An owned native drawing primitive used in typed graph arrays. Construct it from a supported drawing shape and release it after use.',
  Range: 'Half-open integer interval [start, end), used to select matrix rows and columns.',
  TermCriteria: 'Iteration termination settings: combine COUNT and EPS flags to stop at maxCount iterations or the requested epsilon accuracy.',
  Scalar: 'Four numeric channel components. Unused components should be zero; image color order depends on the receiving operation.',
  MinMaxLoc: 'Minimum and maximum values and their two-dimensional locations returned by a matrix reduction.',
  Exception: 'Details of a native OpenCV exception, including its error code, message, function and source location.',
  Circle: 'A detected circle described by its center coordinates and radius.',
  EMDResult: 'Earth mover distance and the scalar lower bound returned alongside the supplied flow output.',
}

export const manualParameters = {
  '_malloc': ['bytes'], '_free': ['pointer'], 'Mat.charAt': ['index0', 'index1', 'index2'],
  'Mat.ucharAt': ['index0', 'index1', 'index2'], 'Mat.shortAt': ['index0', 'index1', 'index2'],
  'Mat.ushortAt': ['index0', 'index1', 'index2'], 'Mat.intAt': ['index0', 'index1', 'index2'],
  'Mat.floatAt': ['index0', 'index1', 'index2'], 'Mat.doubleAt': ['index0', 'index1', 'index2'],
  'ClassHandle.isAliasOf': ['other'],
  'gapi_dnn_Params.new': ['tag', 'net'],
  'GComputation.new': ['inputs', 'outputs'],
  'GComputation.fromMatrices': ['inputs', 'outputs'],
  'UMat.getMat': ['access'],
}

/** Shared documentation for small native families with intentionally sparse upstream comments. */
export const familyDoc = (owner, name) => {
  const key = owner ? owner + '.' + name : name
  const space = text => text.replace(/([a-z\d])([A-Z])/g, '$1 $2').replaceAll('_', ' ').toLowerCase()
  if (/^utils_(?:nested_)?dump/.test(name)) return 'Format the supplied value as text using OpenCV\'s binding diagnostics. Useful for checking how an argument crosses the native boundary.'
  if (/^utils_generateVectorOf/.test(name)) return 'Generate a vector of sample values for OpenCV binding diagnostics; dispose the returned native vector.'
  if (/^utils_(?:nested_)?test/.test(name)) return 'Run OpenCV\'s binding regression helper ' + name + '. This diagnostic exercises argument conversion, overload selection or native exception propagation as indicated by its name.'
  if (/^gapi_(?:ie|ov|onnx)_/.test(owner) || /^gapi_(?:ie|ov|onnx)_params/.test(name)) {
    const action = name.startsWith('cfg') ? 'Configure ' + space(name.slice(3).replace(/\d+$/, '')) : name === 'constInput' ? 'Bind a constant network input' : 'Create network parameter configuration'
    return action + '. These parameter objects describe an optional OpenVINO or ONNX Runtime backend, which is not linked in this WASM build. Use gapi.dnn.Params for executable CPU inference.'
  }
  if (/^GDrawPrim\.from/.test(key)) return 'Wrap the supplied ' + name.slice(4).toLowerCase() + ' shape as an owned native drawing primitive for a graph array. The primitive retains its native value; dispose the returned handle.'
  if (/^gapi_(?:core|imgproc)_(?:cpu|fluid|ocl)_kernels$/.test(name)) return 'Create an owned package of native ' + (name.includes('imgproc') ? 'image-processing' : 'core') + ' graph kernels for the ' + (name.includes('_ocl_') ? 'OpenCL backend. OpenCL acceleration is unavailable in this build' : name.includes('_fluid_') ? 'line-buffered Fluid CPU backend' : 'CPU backend') + '.'
  if (/^reg_MapTypeCaster(?:_|\.)to/.test(key)) return 'Cast a native registration map to the ' + name.replace(/.*to/, '') + ' map interface. The input must contain that map implementation; dispose the returned handle.'
  if (/^rgbd_(?:Rgbd|Odometry)Frame\.release/.test(key)) return name === 'releasePyramids' ? 'Release cached image, depth, normal and gradient pyramids while retaining the source frame data.' : 'Release this RGB-D frame\'s image, depth, normal and cached working storage. The frame handle remains usable.'
  if (/^rgbd_Odometry\.DEFAULT_/.test(key)) return 'Return the native default ' + space(name.slice(8)) + ' used when configuring RGB-D odometry.'
  if (/^linemod_.*\.read/.test(key)) return 'Load LINEMOD modality, detector or class configuration from the supplied file storage. File paths refer to this instance\'s virtual filesystem.'
  if (/^linemod_.*\.write/.test(key)) return 'Serialize LINEMOD configuration or class templates to the supplied file storage in this instance\'s virtual filesystem.'
  if (/^ipp_/.test(name)) return name.includes('get') ? 'Query the native Intel IPP configuration. Intel IPP acceleration is not linked in this WASM build.' : 'Set the native Intel IPP preference. Intel IPP acceleration is not linked in this WASM build, so this does not enable an accelerator.'
  return ''
}

Object.assign(apiDocs, {
  'ccm_ColorCorrectionModel.get_src_rgbl': 'Return the source color samples after conversion to linear RGB for color-correction fitting.',
  'ccm_ColorCorrectionModel.get_dst_rgbl': 'Return the target reference colors in the linear RGB space used for color-correction fitting.',
  'rapid_Tracker.compute': 'Estimate the pose of the tracker\'s configured 3D model from image edges, updating rotation and translation arrays.',
  'rapid_Tracker.clearState': 'Discard the tracker\'s accumulated internal state before tracking a new sequence.',
  'large_kinfu_LargeKinfu.render': 'Raycast the reconstructed scene into the supplied output image, optionally from a specified camera pose.',
  'large_kinfu_LargeKinfu.render1': 'Raycast the reconstructed scene into the output image from the supplied camera pose.',
  'large_kinfu_LargeKinfu.reset': 'Clear the reconstruction volume and reset camera tracking to its initial state.',
  'large_kinfu_LargeKinfu.update': 'Integrate a depth frame into the reconstruction and update the camera pose. Return whether tracking and integration succeeded.',
  'linemod_Modality.name': 'Return the serialized name identifying this LINEMOD feature modality.',
  'linemod_Detector.numTemplates': 'Return the number of stored LINEMOD templates across classes.',
  'linemod_Detector.numTemplates1': 'Return the number of stored LINEMOD templates for the supplied class identifier.',
  'linemod_Detector.numClasses': 'Return the number of object classes stored in this template detector.',
  'linemod_Detector.classIds': 'Return an owned string vector containing the detector\'s object class identifiers.',
  'ximgproc_EdgeDrawing_Params.write': 'Write edge-drawing parameter values to the supplied native file storage.',
  'GMatDesc.withSize': 'Return a matrix descriptor with a new image width and height, retaining its other layout attributes.',
  'sfm_BaseSFM.run': 'Run structure-from-motion reconstruction from tracked 2D points and update the stored cameras and 3D points.',
  'sfm_BaseSFM.run1': 'Reconstruct tracked 2D points, refine the input intrinsic matrix and fill the output rotations, translations and 3D points.',
  'Stitcher.registrationResol': 'Return the image resolution in megapixels used for feature registration.',
  'Stitcher.seamEstimationResol': 'Return the image resolution in megapixels used for seam estimation.',
  'Stitcher.compositingResol': 'Return the image resolution in megapixels used for panorama compositing; a negative value denotes original resolution.',
  'Stitcher.panoConfidenceThresh': 'Return the confidence threshold used to decide whether images belong to the same panorama.',
  'Stitcher.waveCorrection': 'Return whether wave-effect correction is enabled for the estimated camera rotations.',
  'Stitcher.interpolationFlags': 'Return the interpolation mode used when warping panorama images.',
  'Stitcher.workScale': 'Return the scale used to resize input images during feature registration.',
  'detail_FeatherBlender.sharpness': 'Return the sharpness parameter controlling the width of feathered image boundaries.',
  'detail_MultiBandBlender.numBands': 'Return the number of pyramid bands used for multiband image blending.',
  'detail_ExposureCompensator.feed': 'Estimate exposure compensation from overlapping images, their top-left offsets and validity masks.',
  'detail_BundleAdjusterBase.refinementMask': 'Return the mask controlling which camera intrinsic parameters the bundle adjuster refines.',
  'detail_BundleAdjusterBase.confThresh': 'Return the minimum pairwise-match confidence used by bundle adjustment.',
  'detail_BundleAdjusterBase.termCriteria': 'Return the iteration-count and accuracy criteria used to stop bundle adjustment.',
  'detail_GraphCutSeamFinder.find': 'Find graph-cut seams through overlapping images and update the supplied image masks.',
  'detail_Timelapser.initialize': 'Allocate the output canvas from image offsets and sizes before processing the time-lapse sequence.',
  'detail_Timelapser.process': 'Place an image on the time-lapse canvas using its validity mask and top-left offset.',
  'detail_SphericalProjector.mapForward': 'Project an image coordinate onto the configured spherical panorama surface.',
  'detail_SphericalProjector.mapBackward': 'Map a spherical panorama coordinate back to the source image plane.',
  'PyRotationWarper.warpRoi': 'Compute the integer bounding rectangle of an image warped using the supplied intrinsic matrix and camera rotation.',
  'stereo_MatchQuasiDense.apply': 'Return whether this match\'s correlation score is smaller than the supplied match\'s score.',
  'KeyPoint_convert1': 'Convert point coordinates into keypoints with the supplied shared size, response, octave and class identifier.',
  'gapi_wip_draw_render1': 'Render drawing primitives in place on the supplied Y and UV planes of an NV12 image.',
  'GComputation.fromMatrices': 'Construct an owned native graph computation from matrix input and output node vectors.',
  'imwritemulti': 'Encode and save multiple images to a supported multi-page format in the virtual filesystem. Return whether encoding succeeded.',
  'utils_fs_getCacheDirectoryForDownloads': 'Return the native sample-download cache path. The path belongs to the WASM virtual filesystem and does not download files by itself.',
  'utils_nested_OriginalClassName_originalName': 'Return the original class name used by OpenCV\'s class-renaming binding regression helper.',
  'utils_nested_OriginalClassName.originalName': 'Return the original class name used by OpenCV\'s class-renaming binding regression helper.',
  'detail_restoreImageFromLaplacePyrGpu': 'Reconstruct an image from a Laplacian pyramid. This upstream name denotes an OpenCL-oriented helper; accelerated OpenCL execution is unavailable here.',
  'detail_leaveBiggestComponent': 'Keep the largest connected image component under the match-confidence threshold and return its original image indices.',
  'detail_resultRoi': 'Compute the bounding rectangle covering images placed at their supplied top-left offsets.',
  'detail_resultRoi1': 'Compute the bounding rectangle from image offsets and sizes.',
  'detail_resultRoiIntersection': 'Compute the rectangle shared by all images placed at the supplied offsets.',
  'detail_resultTl': 'Return the top-left coordinate of the combined image bounds.',
  'detail_stitchingLogLevel': 'Return the current native stitching diagnostic log level.',
  'samples_findFileOrKeep': 'Look for a sample file and return its resolved path, or keep the original filename if no match is found.',
  'dnn_getAvailableTargets': 'Return an owned vector of execution targets available for a DNN backend in this build. CPU OpenCV inference is enabled.',
  'rgbd_depthTo3dSparse': 'Back-project selected depth-image coordinates into 3D points using the camera intrinsic matrix.',
  'dnn_Net_readFromModelOptimizer1': 'Read an Intel Model Optimizer model from buffers. Its required OpenVINO backend is not linked in this WASM build.',
  'detail_computeImageFeatures': 'Detect keypoints and compute descriptors for the supplied panorama images, optionally using masks.',
  'detail_computeImageFeatures2': 'Detect keypoints and descriptors for one panorama image and return its native image-feature record.',
  'CascadeClassifier_convert': 'Convert a legacy Haar cascade file to the newer cascade serialization format in the virtual filesystem.',
  'CascadeClassifier.convert': 'Convert a legacy Haar cascade file to the newer cascade serialization format in the virtual filesystem.',
  'kinfu_makeVolume': 'Create an owned Kinect Fusion volume using the requested native volume parameters.',
  'legacy_upgradeTrackingAPI': 'Wrap a legacy single-object tracker with the newer Tracker interface and return an owned handle.',
  'MainModule': 'The initialized native WASM module, including its virtual filesystem and memory views. createOpenCV adds typed namespaces and JavaScript helpers.',
  'IntDoublePair': 'An integer and double-precision number passed together as a plain JavaScript value.',
  'GProtoInputArgs': 'An owned input protocol listing the graph nodes accepted by a computation, in execution order.',
  'GProtoOutputArgs': 'An owned output protocol listing the nodes returned by a graph computation, in result order.',
  'linemod_Match.class_id': 'Object class identifier associated with this template match.',
  'TrackerGOTURN_Params.modelTxt': 'Path in the virtual filesystem to the GOTURN network architecture file.',
  'TrackerGOTURN_Params.modelBin': 'Path in the virtual filesystem to the GOTURN trained network weights.',
  'TrackerDaSiamRPN_Params.model': 'Path in the virtual filesystem to the DaSiamRPN tracking model.',
  'TrackerDaSiamRPN_Params.kernel_cls1': 'Path in the virtual filesystem to the DaSiamRPN classification kernel model.',
  'TrackerDaSiamRPN_Params.kernel_r1': 'Path in the virtual filesystem to the DaSiamRPN regression kernel model.',
  'TrackerNano_Params.backbone': 'Path in the virtual filesystem to the Nano tracker feature-extraction network.',
  'TrackerNano_Params.neckhead': 'Path in the virtual filesystem to the Nano tracker neck and prediction-head network.',
  'TrackerVit_Params.net': 'Path in the virtual filesystem to the vision-transformer tracking network.',
  'utils_copyMatAndDumpNamedArguments': 'Copy the supplied matrix to the destination and return a diagnostic string describing the named arguments used by OpenCV\'s binding tests.',
})
