import { writeFile } from 'node:fs/promises'
import ts from 'typescript'
import { namespacePaths } from '../lib/namespaces.js'

// Derive the public bindings from the final augmented API so overloads, factory
// inheritance, graph generics and upstream documentation retain one source of truth.
const program = ts.createProgram(['src/index.ts'], {
  target: ts.ScriptTarget.ESNext, module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler, skipLibCheck: true,
})
const checker = program.getTypeChecker(), source = program.getSourceFile('src/index.ts')
const declaration = source.statements.find(node => ts.isTypeAliasDeclaration(node) && node.name.text === 'OpenCV')
const api = checker.getTypeAtLocation(declaration)
const native = program.getSourceFiles().find(file => file.fileName.endsWith('/lib/opencv.d.ts'))
const nativeTypes = new Set(native.statements.filter(node => ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)).map(node => node.name.text))
// Heap views change after memory growth. Advanced callers obtain current views
// from the initialized instance instead of receiving a stale named snapshot.
const members = new Map(api.getProperties().filter(symbol => !symbol.name.startsWith('_') && !symbol.name.startsWith('HEAP')).map(symbol => [symbol.name, { symbol, path: [symbol.name] }]))
for (const namespace of namespacePaths) {
  const path = namespace.split('.')
  let type = api
  for (const segment of path) type = checker.getTypeOfSymbolAtLocation(type.getProperty(segment), declaration)
  for (const symbol of type.getProperties()) {
    const name = [...path, symbol.name].join('_')
    if (!members.has(name)) members.set(name, { symbol, path: [...path, symbol.name] })
  }
}
const declarations = [...members].map(([name, { symbol, path }]) => {
  const type = checker.getTypeOfSymbolAtLocation(symbol, declaration)
  const docs = symbol.declarations?.flatMap(node => node.jsDoc?.map(doc => doc.getText()) ?? []) ?? []
  const description = docs.sort((a, b) => b.length - a.length)[0]
    ?? `/** ${ts.displayPartsToString(symbol.getDocumentationComment(checker)) || `OpenCV ${name}, available after awaiting initOpenCV().`} */`
  const guarded = type.getCallSignatures().length || type.getConstructSignatures().length || !(type.flags & (ts.TypeFlags.NumberLike | ts.TypeFlags.StringLike | ts.TypeFlags.BooleanLike))
  return `${description}\nexport let ${name}: OpenCV${path.map(segment => `['${segment}']`).join('')}${guarded ? ` = uninitializedExport('${name}')` : ''}\n${nativeTypes.has(name) ? `export type ${name} = import('../lib/opencv.js').${name}\n` : ''}`
})
await writeFile('src/named.ts', `// Generated by scripts/named-exports.mjs. Do not edit.\nimport type { OpenCV } from './index.js'\nimport { registerDefaultBindings, uninitializedExport } from './default.js'\nexport type * from '../lib/opencv.js'\n\n${declarations.join('\n')}\nregisterDefaultBindings(cv => {\n${[...members].map(([name, { path }]) => `  ${name} = cv.${path.join('.')}`).join('\n')}\n})\n`)
console.log(`Generated ${members.size} typed named OpenCV exports`)
